
```{r, message =F}
require(BGLR)
require(here)
require(ggplot2)
require(reshape2)
require(gridExtra)
library(readr)
library(stringr)
library(ggsci)
library(RAINBOWR)
library(lubridate)
```

```{r, message =F, include=FALSE}
# save or read the seed
seedIndCsv <-  here("out","seedInd.csv")
if (file.exists(seedIndCsv)) {
  seedInd <- read.csv(seedIndCsv, row.names = 1, header = T)
  seedInd <- c(as.matrix(seedInd))
} else {
  seedInd <- sample(1:500, 10, replace = F)
  write.csv(x = seedInd, file =  here("out","seedInd.csv"))
}
```


```{r}
pheno19 <- read.csv(here("data", "shoot_blup_all_2019.csv"), row.names = 1)
pheno20 <- read.csv(here("2020", "shoot_blup_all_2020.csv"), row.names = 1)

plot19<-rownames(pheno19)
plot20<-rownames(pheno20)
#table(pheno19$var.id %in% pheno20$var.id)
#table(pheno20$var.id %in% pheno19$var.id)
```

```{r}
grm <- readRDS(here("data", "grm_2.rds"))
head(grm)[,1:3]
```

```{r}
met<- read.csv(here("2019","2019_Tottori_Jul_RootMetabolome_X.csv"))
rownames(met) <- paste0(substr(as.matrix(met[7]),1,2),".",sprintf("%03d",as.matrix(met[8])))
met19 <- met[,10:ncol(met)]
colnames(met19)<- sub("M","X",colnames(met19))

met <- read.csv(here("2020", "2020_Tottori_Main_RootMetabolome.csv"))
rownames(met) <- paste0(substr(as.matrix(met[7]),1,2),".",sprintf("%03d",as.matrix(met[8])))
met20 <- met[,10:ncol(met)]

s_c <- colnames(met19) %in% colnames(met20)
met19<- met19[,s_c]
s_c <- colnames(met20) %in% colnames(met19)
met20<- met20[,s_c]
#table(colnames(met20) == colnames(met19))
```

```{r}
predmet20f19 <- read.csv(here("2020", "2020_predmet_blup_from2019_GM2.csv"), row.names = 1)

predmet19 <- read.csv(here("2019", "2019_predmet_blup.csv"), row.names = 1)
predmet20 <- read.csv(here("2020", "2020_predmet_blup.csv"), row.names = 1)
```

```{r}
com <- read.csv(here("dataFromRiken", "table-from-biom-7.csv"), row.names = 1)
rownames(com) <- gsub(";",".",rownames(com))
com19<- com

#comriken <- read.csv(here("2020", "table-from-biom-7-2020-after.csv"))
com <- read.csv(here("2020", "2020_Tottori_Main_Microbiome_Ratio.csv"))
rownames(com) <- paste0(substr(as.matrix(com[7]),1,2),".",sprintf("%03d",as.matrix(com[8])))
com <- com[,10:ncol(com)]
com20 <- t(com)

s_c <- colnames(com19) %in% colnames(com20)
com19<- com19[,s_c]
s_c <- colnames(com20) %in% colnames(com19)
com20<- com20[,s_c]

dim(com19)
dim(com20)

```


```{r}
CD ="W4"
```


```{r}
selector.grm <- pheno19$var.id %in% rownames(grm)
selector.com <-rownames(pheno19) %in% colnames(com19) 

pl<- list(pheno19,pheno20)
pl.sel<- list()

for (i in 1:2){
pheno<- pl[[i]]
pheno.sel <- pheno[selector.grm & selector.com, ]
#head(pheno.sel)
print(dim(pheno.sel))

selector.cd <- substr(rownames(pheno.sel), 1, 2) == CD
pheno.sel.cd <- pheno.sel[selector.cd, ]
dim(pheno.sel.cd)

plot.id <- rownames(pheno.sel.cd)
rownames(pheno.sel.cd)<-pheno.sel.cd$var.id
pheno.sel.cd$var.id <- plot.id
colnames(pheno.sel.cd)[1]<- "plot.id"
sg <- rownames(grm) %in% rownames(pheno.sel.cd)
gv<-rownames(grm[sg,sg])
pheno.sel.cd<- pheno.sel.cd[gv,]
print(dim(pheno.sel.cd))
pl.sel[[i]]<- pheno.sel.cd
}

psc19<-  pl.sel[[1]] 
psc20<-  pl.sel[[2]]

s_p <- rownames(psc19) %in% rownames(psc20)
psc19<- psc19[s_p,]
s_p <- rownames(psc20) %in% rownames(psc19)
psc20<- psc20[s_p,]

s_p <- colnames(psc19) %in% colnames(psc20)
psc19<- psc19[,s_p]
s_p <- colnames(psc20) %in% colnames(psc19)
psc20<- psc20[,s_p]

table(rownames(psc19) == rownames(psc20))

```


```{r}
var.id <- rownames(psc19)
grm.cd <- grm[var.id, var.id]
plot.id  <- psc19$plot.id
com19.cd <- t(com19[, plot.id])
com19.cd <- scale(com19.cd[, apply(com19.cd, 2, sd) > 0])
#met19ns.cd <- met19[plot.id, ]
met19.cd <- scale(met19[plot.id, ])
#predmet19ns<-predmet19
predmet19<-scale(predmet19)
```


```{r, message =F}
var.id <- rownames(psc20)
grm.cd <- grm[var.id, var.id]
plot.id  <- psc20$plot.id
com20.cd <- t(com20[, plot.id])
com20.cd <- scale(com20.cd[, apply(com20.cd, 2, sd) > 0])
#met20ns.cd <- met20[plot.id, ]
met20.cd <- scale(met20[plot.id, ])
#predmetns20<-predmet20
predmet20<-scale(predmet20)
#predmetns20f19<-predmet20f19
predmet20f19<-scale(predmet20f19)
```


```{r, message =F}
psc <- rbind(psc19,psc20)

s_c <- colnames(com19.cd) %in% colnames(com20.cd)
com19.cd<- com19.cd[,s_c]
s_c <- colnames(com20.cd) %in% colnames(com19.cd)
com20.cd<- com20.cd[,s_c]

s_c <- colnames(com19.cd) %in% colnames(com20.cd)
com19.cd<- com19.cd[,s_c]
s_c <- colnames(com20.cd) %in% colnames(com19.cd)
com20.cd<- com20.cd[,s_c]

mrm19.cd <- tcrossprod(com19.cd) / ncol(com19.cd)
mrm20.cd <- tcrossprod(com20.cd) / ncol(com20.cd)

com.cd<- rbind(com19.cd,com20.cd)
rownames(com.cd)<-rownames(psc)
mrm.cd <- tcrossprod(com.cd) / ncol(com.cd)

metrm19.cd <- tcrossprod(met19.cd) / ncol(met19.cd)
metrm20.cd <- tcrossprod(met20.cd) / ncol(met20.cd)

metPrm19.cd <- tcrossprod(predmet19) / ncol(predmet19)
metPrm20.cd <- tcrossprod(predmet20) / ncol(predmet20)

metPrm20f19.cd <- tcrossprod(predmet20f19) / ncol(predmet20f19)

#metns.cd <- rbind(met19ns.cd,met20ns.cd)
met.cd<- rbind(met19.cd,met20.cd)
rownames(met.cd)<-rownames(psc)
metrm.cd <- tcrossprod(met.cd) / ncol(met.cd)
```

```{r, message =F}
K1 <- grm.cd
K2 <- mrm20.cd
K3 <- metrm20.cd
K8 <- metPrm20f19.cd
K9 <- metPrm20.cd

Z <- design.Z(pheno.labels = rownames(grm.cd),geno.names = rownames(grm.cd))

KZ1<- list(A= list(K = K1, Z = Z))
KZ2<- list(A= list(K = K2, Z = Z))
KZ3<- list(A= list(K = K3, Z = Z))
KZ8<- list(A= list(K = K8, Z = Z))
KZ9<- list(A= list(K = K9, Z = Z))

KZ12<- list(A= list(K = K1, Z = Z),B= list(K = K2, Z = Z))

KZ128<- list(A= list(K = K1, Z = Z),B= list(K = K2, Z = Z),C= list(K = K8, Z = Z))
KZ129<- list(A= list(K = K1, Z = Z),B= list(K = K2, Z = Z),C= list(K = K9, Z = Z))
KZ123<- list(A= list(K = K1, Z = Z),B= list(K = K2, Z = Z),C= list(K = K3, Z = Z))

ZETAlist <- list(KZ1,KZ2,KZ3,KZ8,KZ12,KZ128,KZ129,KZ123)
names(ZETAlist) <- c("KZ1","KZ2","KZ3","KZ8","KZ12","KZ128","KZ129","KZ123")
names<- names(ZETAlist)

```


```{R, message =F, include=FALSE,eval=FALSE}
y <- psc20

resultModelname <- names(ZETAlist)
resultEachModel <- matrix(NA, nrow = length(ZETAlist), ncol = ncol(y)-1)
rownames(resultEachModel) <- names(ZETAlist)
colnames(resultEachModel) <- colnames(y)[2:ncol(y)]

count = 1
for (zl in ZETAlist){
#for (zl in ZETAlist[1]){
  zname = names(ZETAlist)[count]
  print(zname)
  print(count)
  print(c(count,"/",length(ZETAlist)))
  
  var.pheno.all = c() #traitごと結果(要約)
  reslist <- list() #traitごと結果
  
  ZETA <- zl
  X0 <- NULL
  
  # set the seed and cross-validation index
  rep5 <- rep(1:5, 1000)
  rep5 <- rep5[1:nrow(y)]
  
  for (i in 2:ncol(y)){
  #for (i in 2){  
    trait.name <- colnames(y)[i]
    print(c(i,"/",ncol(y)))
    print(trait.name)
    # make the case for the result
    
    
    resultIndex <- c("Correlation", "R2", "RMSE","varU","varE","h2")
    resultEachSeed <- matrix(NA, ncol = length(resultIndex), nrow = length(seedInd))
    colnames(resultEachSeed) <- resultIndex
    rownames(resultEachSeed) <- seedInd
    
    for (seedIndEach in 1:length(seedInd)) {
      # seedIndEach <- 1
      set.seed(seedInd[seedIndEach])
      crossCvInd <- sample(rep5, nrow(y), replace = F)
      
      # prepare the prediction box
      predictionDataRAINBOW <- rep(NA, nrow(y))
      for (times in 1:5) {
        #times <- 1 #危険
        testInd <- crossCvInd == times
        yNa <- y[,i]
        yNa[testInd] <- NA
        
        # RAINBOWR
        resEM3 <- EM3.cpp(y = yNa,
                          X0 = X0, n.core = 1, 
                          ZETA = zl)
        
        # input the predicted data
        predictionDataRAINBOW[testInd] <- resEM3$y.pred[testInd]
      }
      
      # resEM3$weights
      predictData <- (predictionDataRAINBOW)
      obsData <- (y[,i])
      
      # calculate the R2 and RMSE
      correlation <- cor(obsData, predictData)
      R2 <- 1 - sum((obsData - predictData) ^ 2) / sum((obsData - mean(obsData)) ^ 2)
      RMSE <- sqrt(sum((obsData - predictData) ^ 2) / length(obsData))
      VU <- resEM3$Vu
      VE <- resEM3$Ve
      h2 <-  VU/(VU+VE)
      
      # input the result
      resultEachSeed[seedIndEach, ] <- c(correlation, R2, RMSE,VU,VE,h2)
    }
    
    resultsum<- apply(resultEachSeed, 2, mean)
    resultsum<- as.matrix(resultsum)
    colnames(resultsum) <-trait.name
    reslist[[i]]<- resultEachSeed
    #write.csv(resultEachSeed, here("out/pheno", paste0(trait.name, "_rainb.csv" )))
    
    var.pheno.all <- cbind(var.pheno.all,resultsum)
  }
  
  rownames(var.pheno.all) <- resultIndex
  print(var.pheno.all)
  
  resultEachModel[count,]<- var.pheno.all[1,]
  
  count = count +1
}

print(resultEachModel)

for (n in 1:length(names)){
  if (n == 1){
    p <- names[1]
  }
  else{
    p  <- paste(p,names[n],sep="")
  }
}
print(p)
```

```{R,eval=FALSE}
#write.csv(resultEachModel, here("out",paste0("2020_blup",p,"_20f19_",substr(now(),1,10),substr(now(),12,13),".csv" )))
write.csv(resultEachModel, here("out",paste0("2020_blup",p,"_20f20_",substr(now(),1,10),substr(now(),12,13),".csv" )))
```


```{R,fig.dim = c(8, 4),include=TRUE,fig.cap="\\label{fig:figs} Yield Prediction in 2020 (Correlation Coefficients); G is Genome, Micro is Microbiome, TrueMet is actual Metabolome, PredMet_f19 is the Metabolome predicted from Genome and Microbiome in 2019 (Inter-Year Model), PredMet_f19 is the Metabolome predicted from Genome and Microbiome in 2020 (One-Year Model), and + represents the multi-kernel model."}
p<- "KZ1KZ2KZ3KZ8KZ12KZ128KZ129KZ123"
pred.all <- read.csv(here("out",paste0("2020_blup",p,"_20f20_2023-04-2923.csv")),row.names=1)


model.name <- c("G", "Micro", "TrueMet", "PredMet_f19", "G+Micro", "G+Micro+PredMet_f19","G+Micro+PredMet_f20","G+Micro+TrueMet")
trait.name <- colnames(pred.all)
df.all <- NULL


for(i in 1:length(trait.name)) {
  
  pred <-  pred.all[,i]
  df <- data.frame(trait = trait.name[i],model = model.name, mean = pred)
  df.all <- rbind(df.all, df)
}


df.all[df.all < 0] <- 0
df.all$model <- factor(df.all$model, levels = model.name)
df.all$trait <- factor(df.all$trait)
levels(df.all$trait) <- colnames(pred.all)
g <- ggplot(df.all)
g <- g + geom_bar(aes(x = trait, y = mean, fill = model), 
                  stat = "identity",  position = "dodge")
print(g)
```


