---
title: "53_2018_shootblup"
author: "Hayato"
date: "`r Sys.Date()`"
output: html_document
---


# Required packages

```{r, message = T}
require(here)
require(rrBLUP)
```

# Data loading

```{r}
shoot <- read.csv(here("2018", "2018_Tottori_Jul_ShootPhenotype.csv"))

shoot<- shoot[order(shoot$plot,decreasing = FALSE),]
shoot<- shoot[order(shoot$block,decreasing = FALSE),]
#shoot<-na.omit(shoot)
head(shoot)
str(shoot)
```

# BLUP

create data frame
```{r}
# combine block and plot
block.plot <- paste(shoot$block, formatC(shoot$plot, width = 3, flag = "0"), sep = ".")
# new data frame with necessary data
dw <- data.frame(variety = shoot$variety, block = shoot$block, block.plot, shoot[, 10:ncol(shoot)])
# plot id larger than 200 is not necessary in this analysis
dw <- dw[shoot$plot <= 200,]
# choose 4 traits for the analysis
dw <- dw[, -c(6)]
# conver block.plot to a vector of characters and again to a factor
dw$block.plot <- as.factor(as.character(dw$block.plot))
```

calculation (estimation)
```{r}
Z <- model.matrix(~ block.plot - 1, data = dw)
X <- model.matrix(~ block, data = dw)
shoot_est.all <- NULL
#shoot_est <- NULL

for(i in 4:ncol(dw)) {
  print(i)
	y <- dw[,i]
	model <- mixed.solve(y, Z = Z, K = diag(1, ncol(Z)), X = X, method = "REML")
	tmp <- colnames(Z)
	names(model$u) <- substr(tmp, 11, nchar(tmp))
	model$u
	y_est <- model$u
	selector.W1 <- substr(names(model$u), 1, 2) == "C1" 
	y_est[selector.W1] <- y_est[selector.W1] + model$beta[1]
	selector.W2 <- substr(names(model$u), 1, 2) == "C2" 
	y_est[selector.W2] <- y_est[selector.W2] + model$beta[1] + model$beta[2]
	selector.W3 <- substr(names(model$u), 1, 2) == "D1" 
	y_est[selector.W3] <- y_est[selector.W3] + model$beta[1] + model$beta[3]
	selector.W4 <- substr(names(model$u), 1, 2) == "D2" 
	y_est[selector.W4] <- y_est[selector.W4] + model$beta[1] + model$beta[4]
	shoot_est.all <- cbind(shoot_est.all, y_est)
	#shoot_est <- cbind(shoot_est, y_est[selector.C2 | selector.D2])
}
colnames(shoot_est.all) <- colnames(dw)[4:ncol(dw)]
#colnames(shoot_est) <- colnames(dw)[4:ncol(dw)]
```

create a reference of variety names
```{r}
variety <- shoot$variety[shoot$ind == 1]
names(variety) <- block.plot[shoot$ind == 1]
head(variety)
```


output data
```{r}
var.id <- variety[rownames(shoot_est.all)]
df <- data.frame(var.id, shoot_est.all)
write.csv(df, here("data", "shoot_blup_all_2018.csv"), quote = F)
```


