---
title: "67_visualize_pheno"
output: html_document
date: "2024-08-27"
---

```{r}
library(ggplot2)
library(dplyr)
library(here)
library(patchwork)
library(pheatmap)
library(xtable)
source("Script/MyFunctions.R")
```


#G micro met
```{r}

# Condition 1: Drought - BLUP
CD<- "W4"
cd<- "Drought"
res1 <- readRDS(here("out", paste0("yPredYield_BLUPwRF_", CD, "com.RDS")))
g1 <- phl(res1, "BLUP", cd,45)
g1_3_gmm<-phlrf(res1, "BLUP", cd,45)
g1_3_gmm<-phlrf4(res1, "BLUP", cd,45)
g1_3_gmm100<-phlrf100(res1, "BLUP", cd,45)
#print(g1_3_gmm100)
print(g1_3_gmm)
print(g1_3_gmm100)

# Condition 2: Drought - RF
res2 <- readRDS(here("out", paste0("yPredYield_RF_", CD, "com.RDS")))
g2 <- phl(res2, "RF", cd,45)

# Condition 3: Control - BLUP
CD<- "W1"
cd<- "Control"
res3 <- readRDS(here("out", paste0("yPredYield_BLUPwRF_", CD, "com.RDS")))
g3 <- phl(res3, "BLUP", cd,45)
g1_3_gmm<-phlrf4(res3, "BLUP", cd,45)
g1_3_gmm100<-phlrf100(res3, "BLUP", cd,45)

print(g1_3_gmm)
print(g1_3_gmm100)

# Condition 4: Control - RF
res4 <- readRDS(here("out", paste0("yPredYield_RF_", CD, "com.RDS")))
g4 <- phl(res4, "RF", cd,45)

# Combine the four plots using patchwork, sharing a legend
combined_plot <- (g3 + g1) / (g4 + g2) + plot_layout(guides = "collect")

# Display the combineD-plot
print(combined_plot)


file_path <- here("pdf","pheno/gmicro.pdf")
# Open a PDF device
pdf(file = file_path, width = 12, height = 7.5) 
# Create the boxplot
print(combined_plot)
# Close the PDF device
dev.off()


# r1<-res1$resultEachModel[c(7,8,9,10,11),-c(5)]
# r2<-res2$resultEachModel[c(7,8,9,10,11),-c(5)]
# r3<-res3$resultEachModel[c(7,8,9,10,11),-c(5)]
# r4<-res4$resultEachModel[c(7,8,9,10,11),-c(5)]
r1<-res1$resultEachModel[c(7,8,9,10,11),]
r2<-res2$resultEachModel[c(7,8,9,10,11),]
r3<-res3$resultEachModel[c(7,8,9,10,11),]
r4<-res4$resultEachModel[c(7,8,9,10,11),]

rm1<-apply(r1,1,mean)
rm2<-apply(r2,1,mean)
rm3<-apply(r3,1,mean)
rm4<-apply(r4,1,mean)
rs1<-apply(r1,1,sd)
rs2<-apply(r2,1,sd)
rs3<-apply(r3,1,sd)
rs4<-apply(r4,1,sd)

#model.name <- c("G","G+Micro","G+Micro+PredMetBLUPf19","G+Micro+PredMetBLUPf20","G+Micro+PredMetRF_f19","G+Micro+PredMetRF_f20","G+MIcro+TrueMet")

model.name <- c("GMi","GMi+MeB19","GMi+MeB20","GMi+MeR19","GMi+MeR20")
rmat<-rbind(rm1,rm2,rm3,rm4)
colnames(rmat)<-model.name
rownames(rmat)<-c("D-BLUP","D-RF","C-BLUP","C-RF")

rmats<-rbind(rs1,rs2,rs3,rs4)
colnames(rmats)<-model.name
rownames(rmats)<-c("D-BLUP","D-RF","C-BLUP","C-RF")

mean_values <-rmat
sd_values<- rmats
# 平均とSDを交互に並べるマトリックスを作成
formatted_table <- matrix(NA, nrow = nrow(mean_values), ncol = 2 * ncol(mean_values))
for (i in 1:ncol(mean_values)) {
  formatted_table[, 2*i-1] <- mean_values[, i]
  formatted_table[, 2*i] <- sd_values[, i]
}

colnames(formatted_table) <- rep(colnames(mean_values), each = 2)
rownames(formatted_table) <- rownames(mean_values)



heatmap(rmat,cexCol = 0.9,cexRow = 0.9)




boxplot(t(r1),main="Drought BLUP", ylim=c(0.2,0.7),names=model.name)
boxplot(t(r3),main="Control BLUP", ylim=c(0.2,0.7),names=model.name)

# inter inner 
rrx<-rbind(r1[1,],r1[c(4,5),])
rownames(rrx)<-c("GMi","GMi+Met(RF19)","GMi+Met(RF20)")
boxplot(t(rrx),main="GMi+Met Model (Drought)", ylim=c(0.2,0.6),cex.main=1.8,col="coral")


rr<-rbind(r1[1,],r1[c(2,4),],r2[c(2,4),])
rownames(rr)<-c("GMi","GMi+Met(BB)","GMi+Met(RB)","GMi+Met(BR)","GMi+Met(RR)")
boxplot(t(rr),main="Model Selection (Drought)", ylim=c(0.2,0.7))

rr<-rbind(r3[1,],r4[c(2,4),],r4[c(2,4),])
rownames(rr)<-c("GMi","GMi+Met(BB)","GMi+Met(RB)","GMi+Met(BR)","GMi+Met(RR)")
boxplot(t(rr),main="Model Selection (Control)", ylim=c(0.2,0.7))

rr<-rbind(r1[1,],r1[c(3,5),],r2[c(3,5),])
rownames(rr)<-c("GMi","GMi+Met(BB)","GMi+Met(RB)","GMi+Met(BR)","GMi+Met(RR)")
boxplot(t(rr),main="Inter-Model Selection (Drought)", ylim=c(0.2,0.7))

rr<-rbind(r3[1,],r4[c(3,5),],r4[c(3,5),])
rownames(rr)<-c("GMi","GMi+Met(BB)","GMi+Met(RB)","GMi+Met(BR)","GMi+Met(RR)")
boxplot(t(rr),main="Inter-Model Selection (Control)", ylim=c(0.2,0.7))


file_path <- here("pdf","pheno/b1_micro.pdf")
pdf(file = file_path, width = 8, height = 5) 
rr<-rbind(r1[1,],r1[c(2,4),],r2[c(2,4),])
rownames(rr)<-c("GMi","GMi+Met(BB)","GMi+Met(RB)","GMi+Met(BR)","GMi+Met(RR)")
boxplot(t(rr),main="G+Micro+Met Model (Drought)", ylim=c(0.2,0.7),cex.main=1.8
        ,col="coral"
)
dev.off()

file_path <- here("pdf","pheno/b2_micro.pdf")
pdf(file = file_path, width = 8, height = 5) 
rr<-rbind(r3[1,],r4[c(2,4),],r4[c(2,4),])
rownames(rr)<-c("GMi","GMi+Met(BB)","GMi+Met(RB)","GMi+Met(BR)","GMi+Met(RR)")
boxplot(t(rr),main="G+Micro+Met Model (Control)", ylim=c(0.2,0.7),cex.main=1.8
        ,col="cornflowerblue"
)
dev.off()


```

```{r}

r1<-res1$resultEachModel[c(7,8,9,10,11),]
r2<-res2$resultEachModel[c(7,8,9,10,11),]
r3<-res3$resultEachModel[c(7,8,9,10,11),]
r4<-res4$resultEachModel[c(7,8,9,10,11),]

for(data in list(r1,r2,r3,r4)){
#data<-r2
results <- apply(data[-1, ], 1, function(row) {
  wilcox.test(row, data[1, ], paired = TRUE,exact = FALSE)$p.value
})

# 結果を5%水準で判定（p値 < 0.05の場合は「有意差あり」とする）
significance <- ifelse(results < 0.05, "YES", "F")
print(results)    # p値の表示
print(significance)  # 有意差の判断結果

}
```


xtable
```{r}

formatted_mat <- apply(r1, 2, format_without_leading_zero)

rownames(formatted_mat)<-model.name
formatted_mat<-t(formatted_mat)
xtable(formatted_mat )

formatted_mat <- apply(r2, 2, format_without_leading_zero)
rownames(formatted_mat)<-model.name
formatted_mat<-t(formatted_mat)
xtable(formatted_mat )

formatted_mat <- apply(r3, 2, format_without_leading_zero)
rownames(formatted_mat)<-model.name
formatted_mat<-t(formatted_mat)
xtable(formatted_mat )

formatted_mat <- apply(r4, 2, format_without_leading_zero)
rownames(formatted_mat)<-model.name
formatted_mat<-t(formatted_mat)
xtable(formatted_mat )

formatted_mat <- apply(rmat, 2, format_without_leading_zero)
xt<-xtable(formatted_mat)


formatted_mats <- apply(formatted_table[,c(1,2,7,8,9,10)], 2, format_without_leading_zero)
formatted_mats
xtable(formatted_mats)


```
# g met
```{r}
CD<- "W4"
cd<- "Drought"
res1 <- readRDS(here("out", paste0("yPredYield_BLUPwRF_", CD, "com_g.RDS")))
g1 <- phlg(res1, "BLUP", cd,45)
g1_3<-phlgrf(res1, "BLUP", cd,45)
g1_3_100<-phlgrf100(res1, "BLUP", cd,45)

print(g1_3)
print(g1_3_100)

CD<- "W1"
cd<- "Control"
res1 <- readRDS(here("out", paste0("yPredYield_BLUPwRF_", CD, "com_g.RDS")))
g1 <- phlg(res1, "BLUP", cd,45)
g1_3<-phlgrf(res1, "BLUP", cd,45)
g1_3_100<-phlgrf100(res1, "BLUP", cd,45)

print(g1_3)
print(g1_3_100)

CD<- "W4"
cd<- "Drought"

# Condition 2: Drought - RF
res2 <- readRDS(here("out", paste0("yPredYield_RF_", CD, "com_g.RDS")))
g2 <- phlg(res2, "RF", cd,45)

# Condition 3: Control - BLUP
CD<- "W1"
cd<- "Control"
res3 <- readRDS(here("out", paste0("yPredYield_BLUPwRF_", CD, "com_g.RDS")))
g3 <- phlg(res3, "BLUP", cd,45)

# Condition 4: Control - RF
res4 <- readRDS(here("out", paste0("yPredYield_RF_", CD, "com_g.RDS")))
g4 <- phlg(res4, "RF", cd,45)

# Combine the four plots using patchwork, sharing a legend
combined_plot <- (g3 + g1) / (g4 + g2) + plot_layout(guides = "collect")

# Display the combineD-plot
print(combined_plot)

file_path <- here("pdf","pheno/g.pdf")
# Open a PDF device
pdf(file = file_path, width = 12, height = 7.5) 
# Create the boxplot
print(combined_plot)
# Close the PDF device
dev.off()


# 
# r1<-res1$resultEachModel[c(1,7,8,9,10),-c(5)]
# r2<-res2$resultEachModel[c(1,7,8,9,10),-c(5)]
# r3<-res3$resultEachModel[c(1,7,8,9,10),-c(5)]
# r4<-res4$resultEachModel[c(1,7,8,9,10),-c(5)]
r1<-res1$resultEachModel[c(1,7,8,9,10),]
r2<-res2$resultEachModel[c(1,7,8,9,10),]
r3<-res3$resultEachModel[c(1,7,8,9,10),]
r4<-res4$resultEachModel[c(1,7,8,9,10),]
rm1<-apply(r1,1,mean)
rm2<-apply(r2,1,mean)
rm3<-apply(r3,1,mean)
rm4<-apply(r4,1,mean)
rs1<-apply(r1,1,sd)
rs2<-apply(r2,1,sd)
rs3<-apply(r3,1,sd)
rs4<-apply(r4,1,sd)

model.name <- c("G","G+MeB19","G+MeB20","G+MeR19","G+MeR20")

rmat<-rbind(rm1,rm2,rm3,rm4)
colnames(rmat)<-model.name
rownames(rmat)<-c("D-BLUP","D-RF","C-BLUP","C-RF")

rmats<-rbind(rs1,rs2,rs3,rs4)
colnames(rmats)<-model.name
rownames(rmats)<-c("D-BLUP","D-RF","C-BLUP","C-RF")

mean_values <-rmat
sd_values<- rmats
# 平均とSDを交互に並べるマトリックスを作成
formatted_table <- matrix(NA, nrow = nrow(mean_values), ncol = 2 * ncol(mean_values))
for (i in 1:ncol(mean_values)) {
  formatted_table[, 2*i-1] <- mean_values[, i]
  formatted_table[, 2*i] <- sd_values[, i]
}

colnames(formatted_table) <- rep(colnames(mean_values), each = 2)
rownames(formatted_table) <- rownames(mean_values)



heatmap(rmat,cexRow=0.9,cexCol = 0.9)
boxplot(t(r1),main="Drought BLUP", ylim=c(0.2,0.7),names=model.name)
boxplot(t(r3),main="Control BLUP", ylim=c(0.2,0.7),names=model.name)
boxplot(t(r4),main="Control RF", ylim=c(0.2,0.7),names=model.name)


# inter inner 
rr<-rbind(r1[1,],r1[c(4,5),])
rownames(rr)<-c("G","G+Met(RF19)","G+Met(RF20)")
boxplot(t(rr),main="G+Met Model (Drought)", ylim=c(0.2,0.6),cex.main=1.8,col="coral")



file_path <- here("pdf","pheno/b1.pdf")
pdf(file = file_path, width = 8, height = 5) 
rr<-rbind(r1[1,],r1[c(2,4),],r2[c(2,4),])
rownames(rr)<-c("G","G+Met(BB)","G+Met(RB)","G+Met(BR)","G+Met(RR)")
boxplot(t(rr),main="G+Met Model (Drought)", ylim=c(0.2,0.7),cex.main=1.8,col="coral")
dev.off()


file_path <- here("pdf","pheno/b2.pdf")
pdf(file = file_path, width = 8, height = 5) 
rr<-rbind(r3[1,],r4[c(2,4),],r4[c(2,4),])
rownames(rr)<-c("G","G+Met(BB)","G+Met(RB)","G+Met(BR)","G+Met(RR)")
boxplot(t(rr),main="G+Met Model (Control)", ylim=c(0.2,0.7),cex.main=1.8,col="cornflowerblue")

dev.off()


file_path <- here("pdf","pheno/b3.pdf")
pdf(file = file_path, width = 8, height = 5) 
rr<-rbind(r1[1,],r1[c(3,5),],r2[c(3,5),])
rownames(rr)<-c("G","G+Met(BB)","G+Met(RB)","G+Met(BR)","G+Met(RR)")
boxplot(t(rr),main="Inter-Model Selection (Drought)", ylim=c(0.2,0.7),cex.main=1.8,col="coral"
)

dev.off()


file_path <- here("pdf","pheno/b4.pdf")
pdf(file = file_path, width = 8, height = 5) 
rr<-rbind(r3[1,],r4[c(3,5),],r4[c(3,5),])
rownames(rr)<-c("G","G+Met(BB)","G+Met(RB)","G+Met(BR)","G+Met(RR)")
boxplot(t(rr),main="Inter-Model Selection (Control)", ylim=c(0.2,0.7),cex.main=1.8,col="cornflowerblue"
)

dev.off()



```

```{r}


r1<-res1$resultEachModel[c(1,7,8,9,10),]
r2<-res2$resultEachModel[c(1,7,8,9,10),]
r3<-res3$resultEachModel[c(1,7,8,9,10),]
r4<-res4$resultEachModel[c(1,7,8,9,10),]

for(data in list(r1,r2,r3,r4)){
#data<-r2
results <- apply(data[-1, ], 1, function(row) {
  wilcox.test(row, data[1, ], paired = TRUE,exact = FALSE)$p.value
})

# 結果を5%水準で判定（p値 < 0.05の場合は「有意差あり」とする）
significance <- ifelse(results < 0.05, "T", "F")
print(results)    # p値の表示
print(significance)  # 有意差の判断結果

}


```




xtable
```{r}
format_without_leading_zero <- function(x) {
     s <- formatC(x, format="f", digits=3)  # 3桁まで表示
     #s <- sub("^0\\.", ".", s)  # 0.を.に置き換え
     return(s)
}



formatted_mat <- apply(r1, 2, format_without_leading_zero)

rownames(formatted_mat)<-model.name
formatted_mat<-t(formatted_mat)
xtable(formatted_mat )

formatted_mat <- apply(r2, 2, format_without_leading_zero)
rownames(formatted_mat)<-model.name
formatted_mat<-t(formatted_mat)
xtable(formatted_mat )

formatted_mat <- apply(r3, 2, format_without_leading_zero)
rownames(formatted_mat)<-model.name
formatted_mat<-t(formatted_mat)
xtable(formatted_mat )

formatted_mat <- apply(r4, 2, format_without_leading_zero)
rownames(formatted_mat)<-model.name
formatted_mat<-t(formatted_mat)
xtable(formatted_mat )

formatted_mat <- apply(rmat, 2, format_without_leading_zero)
formatted_mat
xtable(formatted_mat)

formatted_mats <- apply(formatted_table[,c(1,2,7,8,9,10)], 2, format_without_leading_zero)
formatted_mats
xtable(formatted_mats)


```



raw bpred
```{R}

CD<- "W4"
cd<- "Drought"
res1 <- readRDS(here("out", paste0("yPredYield_RF_", CD, "com_bpred.RDS")))
g1 <- phlb(res1, "RF", cd,45)

# Condition 2: Drought - RF
res2 <- readRDS(here("out", paste0("yPredYield_RF_", CD, "com_bpred_b.RDS")))
g2 <- phlb(res2, "RF", cd,45,b = TRUE)

# Condition 3: Control - BLUP
CD<- "W1"
cd<- "Control"
res3 <- readRDS(here("out", paste0("yPredYield_RF_", CD, "com_bpred.RDS")))
g3 <- phlb(res3, "RF", cd,45)

# Condition 4: Control - RF
res4 <- readRDS(here("out", paste0("yPredYield_RF_", CD, "com_bpred_b.RDS")))
g4 <- phlb(res4, "RF", cd,45,b=TRUE)

# Combine the four plots using patchwork, sharing a legend
combined_plot <- (g3 + g1) / (g4 + g2) + plot_layout(guides = "collect")

# Display the combineD-plot
print(combined_plot)


# file_path <- here("pdf","pheno/bb.pdf")
# # Open a PDF device
# pdf(file = file_path, width = 12, height = 7.5) 
# Create the boxplot
print(combined_plot)
# Close the PDF device
dev.off()

```

```{r}
r1<-res1$resultEachModel
r2<-res2$resultEachModel
r3<-res3$resultEachModel
r4<-res4$resultEachModel
rm1<-apply(r1,1,mean)
rm2<-apply(r2,1,mean)
rm3<-apply(r3,1,mean)
rm4<-apply(r4,1,mean)
model.name <- c("B19","B20","R19","R20")

rmat<-rbind(rm1,rm2,rm3,rm4)
colnames(rmat)<-model.name
rownames(rmat)<-c("D by Pred","D by True","C by Pred","C by Pred")

rmat
formatted_mat <- apply(rmat, 2, format_without_leading_zero)
formatted_mat
xtable(formatted_mat)


heatmap(rmat,cexRow=1,cexCol = 1)
```


```{r,fig.width=5,fig.height=5}
par(pty="s")
plot(r2, r1, xlim = c(0, 1), ylim = c(0, 1), pch=1:4,
     ylab="Trained by Predicted Met", xlab="Trained by True Met",
     main="Metabolome Prediction",cex.main=1.4,cex=1.2)

lg<-c("BLUP19","BLUP20","RF19","RF20")
# y = x の線を追加
abline(0, 1, col=2)

# レジェンドを追加
legend("topleft", legend=lg, pch=1:4)
par()
```


W4
```{r,fig.width=5,fig.height=5}
par(pty="s")
CD<- "W4"
cd<- "Drought"
res1 <- readRDS(here("out", paste0("yPredYield_RF_", CD, "com_bpred_gm.RDS")))
#g1 <- phlb(res1, "RF", cd,45)

# Condition 2: Drought - RF
res2 <- readRDS(here("out", paste0("yPredYield_RF_", CD, "com_bpred_b_gm.RDS")))

res5 <- readRDS(here("out", paste0("yPredYield_BLUP_", CD, "com_bpred_gm.RDS")))
res5_2 <- readRDS(here("out", paste0("yPredYield_BLUP_", CD, "com_bpred_gm_912.RDS")))

res6 <- readRDS(here("out", paste0("yPredYield_BLUP_", CD, "com_bpred_b1_gm.RDS")))
res7 <- readRDS(here("out", paste0("yPredYield_BLUP_", CD, "com_bpred_b2_gm.RDS")))
res8 <- readRDS(here("out", paste0("yPredYield_BLUP_", CD, "com_bpred_b9_gm.RDS")))
res9 <- readRDS(here("out", paste0("yPredYield_BLUP_", CD, "com_bpred_b12_gm.RDS")))


r1<-res1$resultEachModel
r2<-res2$resultEachModel
r5<-res5$resultEachModel
r5_2<-res5_2$resultEachModel

r6<-res6$resultEachModel
r7<-res7$resultEachModel
r8<-res8$resultEachModel
r9<-res9$resultEachModel

rb<- rbind(r5[1,],r5_2[1,],r5[2,],r5_2[2,])
rb_b<- rbind(r6,r8,r7,r9)

r2b<- rbind(r1[c(3,4),],rb[c(3,4),])
r2b_b<- rbind(r2[c(3,4),],rb_b[c(3,4),])

plot(r2b_b,r2b, xlim = c(0, 1), ylim = c(0, 1), pch=1:4,
     ylab="Trained by G + Micro + Predicted Met", xlab="Trained by  G + Micro + True Met",
     main="Phenotype Prediction (Drought)",cex.main=1.4,cex=1.2)

lg<-c("RF-RF19","RF-RF20","RF-BLUP19","RF-BLUP20")
# y = x の線を追加
abline(0, 1, col=2)

# レジェンドを追加
legend("topleft", legend=lg, pch=1:4)

b2r<- rbind(r1[-c(3,4),],rb[-c(3,4),])
b2r_b<- rbind(r2[-c(3,4),],rb_b[-c(3,4),])

plot(b2r_b,b2r, xlim = c(0, 1), ylim = c(0, 1), pch=1:4,
     ylab="Trained by G + Micro + Predicted Met", xlab="Trained by  G + Micro + True Met",
     main="Phenotype Prediction (Drought)",cex.main=1.4,cex=1.2)

lg<-c("BLUP-BLUP19","BLUP-BLUP20","BLUP-RF19","BLUP-RF20")
# y = x の線を追加
abline(0, 1, col=2)

# レジェンドを追加
legend("topleft", legend=lg, pch=1:4)


b<- rbind(r2b,b2r)
b_b<- rbind(r2b_b,b2r_b)


plot(b_b,b, xlim = c(0, 1), ylim = c(0, 1), pch=1:8,
     ylab="Trained by G + Micro + Predicted Met", xlab="Trained by  G + Micro + True Met",
     main="Phenotype Prediction (Drought)",cex.main=1.4,cex=1.2)

lg<-c("RF-RF19","RF-RF20","RF-BLUP19","RF-BLUP20","BLUP-BLUP19","BLUP-BLUP20","BLUP-RF19","BLUP-RF20")
# y = x の線を追加
abline(0, 1, col=2)

# レジェンドを追加
legend("topleft", legend=lg, pch=1:8)

plot(b_b, b, xlim = c(0, 1), ylim = c(0, 1), pch = 1:4, col = rep(c("blue", "red"), each = 4),
     ylab = "Trained by G + Micro + Predicted Met", 
     xlab = "Trained by G + Micro + True Met",
     main = "Phenotype Prediction (Drought)", cex.main = 1.4, cex = 1.2)

lg <- c("RF-RF19", "RF-RF20", "RF-BLUP19", "RF-BLUP20", "BLUP-BLUP19", "BLUP-BLUP20", "BLUP-RF19", "BLUP-RF20")

# y = x の線を追加
abline(0, 1, col = 2)

# レジェンドを追加（色分け）
legend("topleft", legend = lg, pch = 1:4, col = rep(c("blue", "red"), each = 4))

par()
```


W1
```{r,fig.width=5,fig.height=5}
par(pty="s")
CD<- "W1"
cd<- "Control"
res1 <- readRDS(here("out", paste0("yPredYield_RF_", CD, "com_bpred_gm.RDS")))
#g1 <- phlb(res1, "RF", cd,45)

# Condition 2: Drought - RF
res2 <- readRDS(here("out", paste0("yPredYield_RF_", CD, "com_bpred_b_gm.RDS")))

res5 <- readRDS(here("out", paste0("yPredYield_BLUP_", CD, "com_bpred_gm.RDS")))
res5_2 <- readRDS(here("out", paste0("yPredYield_BLUP_", CD, "com_bpred_gm_912.RDS")))

res6 <- readRDS(here("out", paste0("yPredYield_BLUP_", CD, "com_bpred_b1_gm.RDS")))
res7 <- readRDS(here("out", paste0("yPredYield_BLUP_", CD, "com_bpred_b2_gm.RDS")))
res8 <- readRDS(here("out", paste0("yPredYield_BLUP_", CD, "com_bpred_b9_gm.RDS")))
res9 <- readRDS(here("out", paste0("yPredYield_BLUP_", CD, "com_bpred_b12_gm.RDS")))


r1<-res1$resultEachModel
r2<-res2$resultEachModel
r5<-res5$resultEachModel
r5_2<-res5_2$resultEachModel

r6<-res6$resultEachModel
r7<-res7$resultEachModel
r8<-res8$resultEachModel
r9<-res9$resultEachModel

rb<- rbind(r5[1,],r5_2[1,],r5[2,],r5_2[2,])
rb_b<- rbind(r6,r8,r7,r9)

r2b<- rbind(r1[c(3,4),],rb[c(3,4),])
r2b_b<- rbind(r2[c(3,4),],rb_b[c(3,4),])

plot(r2b_b,r2b, xlim = c(0, 1), ylim = c(0, 1), pch=1:4,
     ylab="Trained by G + Micro + Predicted Met", xlab="Trained by  G + Micro + True Met",
     main="Phenotype Prediction (Control)",cex.main=1.4,cex=1.2)

lg<-c("RF-RF19","RF-RF20","RF-BLUP19","RF-BLUP20")
# y = x の線を追加
abline(0, 1, col=2)

# レジェンドを追加
legend("topleft", legend=lg, pch=1:4)

b2r<- rbind(r1[-c(3,4),],rb[-c(3,4),])
b2r_b<- rbind(r2[-c(3,4),],rb_b[-c(3,4),])

plot(b2r_b,b2r, xlim = c(0, 1), ylim = c(0, 1), pch=1:4,
     ylab="Trained by G + Micro + Predicted Met", xlab="Trained by  G + Micro + True Met",
     main="Phenotype Prediction (Control)",cex.main=1.4,cex=1.2)

lg<-c("BLUP-BLUP19","BLUP-BLUP20","BLUP-RF19","BLUP-RF20")
# y = x の線を追加
abline(0, 1, col=2)

# レジェンドを追加
legend("topleft", legend=lg, pch=1:4)


b<- rbind(r2b,b2r)
b_b<- rbind(r2b_b,b2r_b)


plot(b_b,b, xlim = c(0, 1), ylim = c(0, 1), pch=1:8,
     ylab="Trained by G + Micro + Predicted Met", xlab="Trained by  G + Micro + True Met",
     main="Phenotype Prediction (Control)",cex.main=1.4,cex=1.2)

lg<-c("RF-RF19","RF-RF20","RF-BLUP19","RF-BLUP20","BLUP-BLUP19","BLUP-BLUP20","BLUP-RF19","BLUP-RF20")
# y = x の線を追加
abline(0, 1, col=2)

# レジェンドを追加
legend("topleft", legend=lg, pch=1:8)

plot(b_b, b, xlim = c(0, 1), ylim = c(0, 1), pch = 1:4, col = rep(c("blue", "red"), each = 4),
     ylab = "Trained by G + Micro + Predicted Met", 
     xlab = "Trained by G + Micro + True Met",
     main = "Phenotype Prediction (Control)", cex.main = 1.4, cex = 1.2)

lg <- c("RF-RF19", "RF-RF20", "RF-BLUP19", "RF-BLUP20", "BLUP-BLUP19", "BLUP-BLUP20", "BLUP-RF19", "BLUP-RF20")

# y = x の線を追加
abline(0, 1, col = 2)

# レジェンドを追加（色分け）
legend("topleft", legend = lg, pch = 1:4, col = rep(c("blue", "red"), each = 4))

par()
```



