---
title: '69'
author: "Hayato Yoshioka"
date: "2025-01-04"
output: html_document
---

RDA classic 
Refer to Script/6_4 soybean_two for original

genome 3000 is the best . 

Scale or not

all data too

```{r, message =F}
require(BGLR)
library(dplyr)
require(here)
require(ggplot2)
# require(reshape2)
# require(gridExtra)
# library(readr)
library(stringr)
# library(ggsci)
library(RAINBOWR)
# library(lubridate)
library(foreach)
library(future)
library(doFuture)
# library(doRNG)
library(tictoc)
library(doSNOW)
library(purrr)
source("Script/MyFunctions.R")
# library(vegan)
# library(VARshrink)
# library(ggplot2)
# library(glmnet)
# library(lars)
require(ranger)
# require(ggrepel)
# require(tidyverse)
library(rrda)

getwd()
```

seed
```{r, message =F}
# save or read the seed
seedIndCsv <-  here("out","seedInd.csv")
if (file.exists(seedIndCsv)) {
  seedInd <- read.csv(seedIndCsv, row.names = 1, header = T)
  seedInd <- c(as.matrix(seedInd))
} else {
  seedInd <- sample(1:500, 10, replace = F)
  write.csv(x = seedInd, file =  here("out","seedInd.csv"))
}
```

```{r}
Data<-readRDS(here("data/two/two2019.RDS"))
#predmet<-readRDS(here("out","Soy",cd,"predmmet_gmicro_rda.RDS"))

genome<-Data$genome3k
grm<-Data$grm
met<-Data$met
mic<-Data$mic
mir<-Data$mir
pheno<-Data$pheno

cd<-Data$cd

if (cd == "Drought"){
	CD<-"W4"
} else if (cd=="Control"){
	CD<-"W1"
}

```

## rn all
```{r,eval=F}
set.seed(123)
# Define number of lambdas and the lambda sequence

n_lam <- 50
#Lambda <- exp(seq(-8, 20, length.out = n_lam))
Lambda <- exp(seq(0, 20, length.out = n_lam))


# Define X and Y sets with descriptive names
X_set <- list(genome, grm, met, mic, mir, cbind(genome,mic), cbind(genome,mir))                 # X options
X_names <- c("genome","grm","metabolome", "micro_c", "micro_r","genome micro_c","genome micro_r")  # Descriptive X names
Y_set <- list(pheno,met)       # Y options
Y_names <- c("phenotype","metabolome")  # Descriptive Y names


ni<-c(1,4,6,7)
nj<-c(2,2,2,2)

# Loop over all combinations of X and Y

for (k in 1:length(ni)){

    i<-ni[k]
    j<-nj[k]
    
    X <- X_set[[i]]  # Select X
    Y <- Y_set[[j]]  # Select Y
    
    # Convert X and Y to matrix format
    X <- as.matrix(X)
    Y <- as.matrix(Y)
    
    pred_Yall<-matrix(NA,nrow(Y),ncol(Y))
    

        plan(multisession)
        #tic()
        cv_result <- rrda.cv(X = X, Y = Y,lambda = Lambda,maxrank = 30,verbose = F)
        #toc()
        plan(sequential)
        #sink()
        # Extract optimal lambda and rank
        L <- cv_result$opt_min$lambda
        K <- cv_result$opt_min$rank
        
        p<-rrda.plot(cv_result)
        print(p)
        rrda.summary(cv_result)
 
}
    
```


## rn for roop LOO4
```{r}
set.seed(123)
# Define number of lambdas and the lambda sequence

n_lam <- 50
#Lambda <- exp(seq(-8, 20, length.out = n_lam))
Lambda <- exp(seq(0, 20, length.out = n_lam))


# Define X and Y sets with descriptive names
X_set <- list(genome, grm, met, mic, mir, cbind(genome,mic), cbind(genome,mir))                 # X options
X_names <- c("genome","grm","metabolome", "micro_c", "micro_r","genome micro_c","genome micro_r")  # Descriptive X names
Y_set <- list(pheno,met)       # Y options
Y_names <- c("phenotype","metabolome")  # Descriptive Y names

ni<-c(7)
nj<-c(1)

#ni<-c(1,2,3,4,5,6,7)
#nj<-c(1,1,1,1,1,1,1)

# Loop over all combinations of X and Y

cmat<- matrix(NA,length(ni),ncol(pheno))
colnames(cmat)<-colnames(pheno)
rownames(cmat)<-X_names[ni]

for (k in 1:length(ni) ){
 
    i<-ni[k]
    j<-nj[k]
    
    X <- X_set[[i]]  # Select X
    Y <- Y_set[[j]]  # Select Y
    
    # Convert X and Y to matrix format
    X <- as.matrix(X)
    Y <- as.matrix(Y)
    
    pred_Yall<-matrix(NA,nrow(Y),ncol(Y))
    
    pb <- txtProgressBar(min = 0, max =nrow(X) , style = 3)
    for (rn in 1: nrow(X)){
    #for (rn in 1:2){
        X_train<-X[-rn,]
        X_test<-X[rn,,drop=F]
        Y_train<-Y[-rn,]
        Y_test<-Y[rn,,drop=F]
        
        # Perform cross-validation using rrda
        #sink("/dev/null")
        plan(multisession)
        #tic()
        cv_result <- rrda.cv(X = X_train, Y = Y_train,lambda = Lambda,maxrank = 9,nfold = 5,verbose = F)
        #toc()
        plan(sequential)
        #sink()
        # Extract optimal lambda and rank
        L <- cv_result$opt_min$lambda
        K <- cv_result$opt_min$rank
        
        # Fit the model using the optimal lambda and rank
        b <- rrda.fit(Y = Y_train, X = X_train, lambda = L, nrank = K,scale.X = F,scale.Y = F)
        
        # Predict Y using the fitted model
        pred_Y <- rrda.predict(b, X_test, lambda = L, nrank = K)[[1]][[1]][[1]]
        pred_Yall[rn,]<- pred_Y
        setTxtProgressBar(pb, rn)
        }
        close(pb)
        

        PY<-list(pred_Yall=pred_Yall,Y=Y)
        saveRDS(PY,here("out","Soy",cd,paste0("Pred_X=", X_names[i], "Y=", Y_names[j],cd,"gm2019_LOO_5raf.RDS")))
        Y <- PY$Y
        pred_Yall <- PY$pred_Yall
        
        cor<-diag(cor(Y,pred_Yall))
        cmat[k,]<-cor
        }
saveRDS(cmat,here("out","Soy",cd,"cor_gm2019_LOO_5raf.RDS"))
print(cmat)
```

plot for RDA results
inputs: genome met micro g+micro
```{R,fig.dim = c(8, 4)}
pred.all<-readRDS(here("out","Soy",cd,"cor_gm2019_LOO.RDS"))
model.name <- rownames(pred.all)
#model.name <- c("G","Met","Micro","Micro_proc","G + Micro")
#model.name <- c("G","Met","Micro","G + Micro")

#pred.all2<-readRDS(here("out","Soy",cd,"cor_gm2019_LOO_2.RDS"))
# 
# 
# pred.all[1,]<-pred.all2[1,]
# pred.all[5,]<-pred.all2[2,]
# pred.all<-pred.all[-4,]

trait.name <- colnames(pred.all) %>% sort() #sort
pred.all<- data.frame(pred.all) %>% select(trait.name)
df.all <- NULL


for(i in 1:length(trait.name)) {
  
  pred <-  pred.all[,i]
  df <- data.frame(trait = trait.name[i],model = model.name, mean = pred)
  df.all <- rbind(df.all, df)
}

df.all[df.all < 0] <- 0
df.all$model <- factor(df.all$model, levels = model.name)
df.all$trait <- factor(df.all$trait)
levels(df.all$trait) <- colnames(pred.all)
g <- ggplot(df.all)
g <- g + geom_bar(aes(x = trait, y = mean, fill = model), 
                  stat = "identity",  position = "dodge")  
g <- g + ggtitle(paste0("Yield Prediction ridge RDA in 2019 ",cd))
g <- g + ylab("COR")
g <- g + xlab("")
g <- g + ylim(0,0.90)

g <- g + theme(axis.text.x = element_text(angle = 60, hjust=1))

print(g)

```

# vs BLUP
plot to compare the results in BLUP
```{r}
res<-readRDS(here("out", paste0("yPredYield_BLUPwRF_", CD, "com.RDS")))
p<-res$p
pred.all<-res$resultEachModel

pred.all<- pred.all[c(1,3,2,7,10),]

model.name <- c("G","Met","Micro","G+Micro","G+Micro+PredMetRF")

rda<-readRDS(here("out","Soy",cd,"cor_gm2019_LOO.RDS"))
rda5<-rda[5,]

#rda<-readRDS(here("out","Soy",cd,"cor_gm2019_LOO_5raf.RDS"))
#rda5<-rda[1,]


#rda<-readRDS(paste0("/Users/hayatoyoshioka/Documents/R/HayatoINRAE/out/Soy/",cd,"cor_gm2019_LOOg16.RDS"))
#rda5<-rda[2,]

pred.all<-rbind(pred.all,rda5)


model.name <- c("G (BLUP)","Met (BLUP)","Micro (BLUP)","G+Micro (BLUP)","G+Micro+PredMetRF (BLUP)","G+Micro (ridge RDA)")


trait.name <- colnames(pred.all) %>% sort() #sort
pred.all<- data.frame(pred.all) %>% select(trait.name)
df.all <- NULL


for(i in 1:length(trait.name)) {
  
  pred <-  pred.all[,i]
  df <- data.frame(trait = trait.name[i],model = model.name, mean = pred)
  df.all <- rbind(df.all, df)
}

df.all[df.all < 0] <- 0
df.all$model <- factor(df.all$model, levels = model.name)
df.all$trait <- factor(df.all$trait)
levels(df.all$trait) <- colnames(pred.all)
g <- ggplot(df.all)
g <- g + geom_bar(aes(x = trait, y = mean, fill = model), 
                  stat = "identity",  position = "dodge")  
g <- g + ggtitle(paste0("Yield Prediction in 2019 ",cd))
g <- g + ylim(0,0.90)
g <- g + ylab("COR")
g <- g + xlab("")

g <- g + theme(axis.text.x = element_text(angle = 60, hjust=1))

print(g)
```

new data  (micro:update)

summary
```{r}
res<-readRDS(here("out", paste0("yPredYield_BLUPwRF_", CD, "com.RDS")))
p<-res$p
pred.all<-res$resultEachModel

pred.all<- pred.all[c(1,3,2,7,10),]

res2<-readRDS(here("out", paste0("yPredYield_BLUP_micro_count_gmicrometK13", CD, "com.RDS")))
pred.all2<-res2$resultEachModel



gmicrocount<-readRDS(here("out", paste0("yPredYield_BLUP_micro_gmicro_count_", CD, "com.RDS")))
gmicrocountres<-gmicrocount$resultEachModel[2,]

microcount<-readRDS(here("out", paste0("yPredYield_BLUP_micro_count_", CD, "com.RDS")))
microcountres<-microcount$resultEachModel

pred_count<-readRDS(here("out", paste0("yPredYield_BLUP_micro_count_withRFpredRDApred3", CD, "com.RDS")))
predcountres<-pred_count$resultEachModel[1,]
gmr<-pred_count$resultEachModel[2,]
# 75
pred.all[3,]<-microcountres
pred.all[4,]<-gmicrocountres
pred.all[5,]<-predcountres

#model.name <- c("G","Met","Micro","G+Micro","G+Micro+PredMetRF")
rda<-readRDS(here("out","Soy",cd,"cor_gm2019_LOO.RDS"))
rda5<-rda[5,]

#rda<-readRDS(paste0("/Users/hayatoyoshioka/Documents/R/HayatoINRAE/out/Soy/",cd,"cor_gm2019_LOOg16.RDS"))
#rda5<-rda[2,]

pred.all<-rbind(pred.all,rda5,gmr,pred.all2)
pred.all<-pred.all[c(1,4,5,10),]
pred.all<-rbind(pred.all,preall2)

model.name <- c("G+Micro (BLUP)","G+Micro+PredMetRF (BLUP)","G+Micro (ridge RDA)")


trait.name <- colnames(pred.all) %>% sort() #sort
pred.all<- data.frame(pred.all) %>% select(trait.name)
df.all <- NULL


for(i in 1:length(trait.name)) {
  
  pred <-  pred.all[,i]
  df <- data.frame(trait = trait.name[i],model = model.name, mean = pred)
  df.all <- rbind(df.all, df)
}

df.all[df.all < 0] <- 0
df.all$model <- factor(df.all$model, levels = model.name)
df.all$trait <- factor(df.all$trait)
levels(df.all$trait) <- colnames(pred.all)
g <- ggplot(df.all)
g <- g + geom_bar(aes(x = trait, y = mean, fill = model), 
                  stat = "identity",  position = "dodge")  
g <- g + ggtitle(paste0("Yield Prediction in 2019 ",cd))
g <- g + ylim(0,0.90)
g <- g + ylab("COR")
g <- g + xlab("")

g <- g + theme(axis.text.x = element_text(angle = 60, hjust=1))

print(g)
```

```{r}
res<-readRDS(here("out", paste0("yPredYield_BLUPwRF_", CD, "com.RDS")))
p<-res$p
pred.all<-res$resultEachModel

pred.all<- pred.all[c(1,3,2,7,10),]

res<-readRDS(here("out", paste0("yPredYield_BLUPwRF_", CD, "com.RDS")))
pred.all2<-res$resultEachModel


gmicrocount<-readRDS(here("out", paste0("yPredYield_BLUP_micro_gmicro_count_", CD, "com.RDS")))
gmicrocountres<-gmicrocount$resultEachModel[2,]

microcount<-readRDS(here("out", paste0("yPredYield_BLUP_micro_count_", CD, "com.RDS")))
microcountres<-microcount$resultEachModel

pred_count<-readRDS(here("out", paste0("yPredYield_BLUP_micro_count_withRFpredRDApred3", CD, "com.RDS")))
predcountres<-pred_count$resultEachModel[1,]
gmr<-pred_count$resultEachModel[2,]
# 75
pred.all[3,]<-microcountres
pred.all[4,]<-gmicrocountres
pred.all[5,]<-predcountres

#model.name <- c("G","Met","Micro","G+Micro","G+Micro+PredMetRF")
rda<-readRDS(here("out","Soy",cd,"cor_gm2019_LOO.RDS"))
rda5<-rda[5,]

#rda<-readRDS(paste0("/Users/hayatoyoshioka/Documents/R/HayatoINRAE/out/Soy/",cd,"cor_gm2019_LOOg16.RDS"))
#rda5<-rda[2,]

pred.all<-rbind(pred.all,rda5,gmr)
pred.all<-pred.all[c(4,5,6),]


model.name <- c("G+Micro (BLUP)","G+Micro+PredMetRF (BLUP)","G+Micro (ridge RDA)")


trait.name <- colnames(pred.all) %>% sort() #sort
pred.all<- data.frame(pred.all) %>% select(trait.name)
df.all <- NULL


for(i in 1:length(trait.name)) {
  
  pred <-  pred.all[,i]
  df <- data.frame(trait = trait.name[i],model = model.name, mean = pred)
  df.all <- rbind(df.all, df)
}

df.all[df.all < 0] <- 0
df.all$model <- factor(df.all$model, levels = model.name)
df.all$trait <- factor(df.all$trait)
levels(df.all$trait) <- colnames(pred.all)
g <- ggplot(df.all)
g <- g + geom_bar(aes(x = trait, y = mean, fill = model), 
                  stat = "identity",  position = "dodge")  
g <- g + ggtitle(paste0("Yield Prediction in 2019 ",cd))
g <- g + ylim(0,0.90)
g <- g + ylab("COR")
g <- g + xlab("")

g <- g + theme(axis.text.x = element_text(angle = 60, hjust=1))

print(g)
```

all
```{r}
res<-readRDS(here("out", paste0("yPredYield_BLUPwRF_", CD, "com.RDS")))
p<-res$p
pred.all<-res$resultEachModel

pred.all<- pred.all[c(1,3,2,7,10),]


gmicrocount<-readRDS(here("out", paste0("yPredYield_BLUP_micro_gmicro_count_", CD, "com.RDS")))
gmicrocountres<-gmicrocount$resultEachModel[2,]

microcount<-readRDS(here("out", paste0("yPredYield_BLUP_micro_count_", CD, "com.RDS")))
microcountres<-microcount$resultEachModel

pred_count<-readRDS(here("out", paste0("yPredYield_BLUP_micro_count_withRFpredRDApred3", CD, "com.RDS")))
predcountres<-pred_count$resultEachModel[1,]
gmr<-pred_count$resultEachModel[2,]
# 75
pred.all[3,]<-microcountres
pred.all[4,]<-gmicrocountres
pred.all[5,]<-predcountres

model.name <- c("G","Met","Micro","G+Micro","G+Micro+PredMetRF")

rda<-readRDS(here("out","Soy",cd,"cor_gm2019_LOO.RDS"))
rda5<-rda[5,]

#rda<-readRDS(paste0("/Users/hayatoyoshioka/Documents/R/HayatoINRAE/out/Soy/",cd,"cor_gm2019_LOOg16.RDS"))
#rda5<-rda[2,]

pred.all<-rbind(pred.all,rda5,gmr)


model.name <- c("G (BLUP)","Met (BLUP)","Micro (BLUP)","G+Micro (BLUP)","G+Micro+PredMetRF (BLUP)","G+Micro (ridge RDA)","G+Micro+predmetRDA (BLUP)")


trait.name <- colnames(pred.all) %>% sort() #sort
pred.all<- data.frame(pred.all) %>% select(trait.name)
df.all <- NULL


for(i in 1:length(trait.name)) {
  
  pred <-  pred.all[,i]
  df <- data.frame(trait = trait.name[i],model = model.name, mean = pred)
  df.all <- rbind(df.all, df)
}

df.all[df.all < 0] <- 0
df.all$model <- factor(df.all$model, levels = model.name)
df.all$trait <- factor(df.all$trait)
levels(df.all$trait) <- colnames(pred.all)
g <- ggplot(df.all)
g <- g + geom_bar(aes(x = trait, y = mean, fill = model), 
                  stat = "identity",  position = "dodge")  
g <- g + ggtitle(paste0("Yield Prediction in 2019 ",cd))
g <- g + ylim(0,0.90)
g <- g + ylab("COR")
g <- g + xlab("")

g <- g + theme(axis.text.x = element_text(angle = 60, hjust=1))

print(g)
```

