---
title: "61_YieldPrediction_RF_2019"
output: html_document
date: "2023-11-30"
---

note (maybe)

BLUP with RF
required packages


```{r, message =F}
require(BGLR)
library(dplyr)
require(here)
require(ggplot2)
# require(reshape2)
# require(gridExtra)
# library(readr)
library(stringr)
# library(ggsci)
library(RAINBOWR)
# library(lubridate)
library(foreach)
library(future)
library(doFuture)
# library(doRNG)
library(tictoc)
library(doSNOW)
library(purrr)
source("Script/MyFunctions.R")
# library(vegan)
# library(VARshrink)
# library(ggplot2)
# library(glmnet)
# library(lars)
require(ranger)
# require(ggrepel)
# require(tidyverse)
library(rrda)

getwd()
```

seed
```{r, message =F}
# save or read the seed
seedIndCsv <-  here("out","seedInd.csv")
if (file.exists(seedIndCsv)) {
  seedInd <- read.csv(seedIndCsv, row.names = 1, header = T)
  seedInd <- c(as.matrix(seedInd))
} else {
  seedInd <- sample(1:500, 10, replace = F)
  write.csv(x = seedInd, file =  here("out","seedInd.csv"))
}
```

read phenotypic data
```{r}
pheno18 <- read.csv(here("2018", "shoot_blup_all_2018.csv"), row.names = 1)
pheno19 <- read.csv(here("2019", "shoot_blup_all_2019.csv"), row.names = 1)
pheno20 <- read.csv(here("2020", "shoot_blup_all_2020.csv"), row.names = 1)

plot18<-rownames(pheno18)
plot19<-rownames(pheno19)
plot20<-rownames(pheno20)

var18<-pheno18$var.id
var19<-pheno19$var.id
var20<-pheno20$var.id
```

read genomic relationship matrix data
```{r}
grm <- readRDS(here("data", "grm_2.rds"))
head(grm)[,1:3]
```
```{r}

bm<- readRDS(here("data/genome","genoMarker_LD0.9_SNP234781.RDS"))
bm2<- readRDS(here("data/genome","genoMarker_LD0.5_SNP64438.RDS"))
bm3<- readRDS(here("data/genome","genoMarker_LD0.1_SNP16419.RDS"))
bm4<- readRDS(here("data/genome","genoMarker_LD0.001_SNP3078.RDS"))

file.geno <- list.files(here("data/genome/"),full.names = TRUE) %>% 
 str_subset(.,pattern='RDS') %>% 
 setNames(.,.) %>% 
 .[1:4] 
 
Geno <- map(file.geno, readRDS)
names(Geno)

head(bm)[,1:3]

genome <- as.matrix(bm4)
dim(genome)
```


read metabolomic data
```{r}
met<- read.csv(here("2019","2019_Tottori_Jul_RootMetabolome_X.csv"))
rownames(met) <- paste0(substr(as.matrix(met[7]),1,2),".",sprintf("%03d",as.matrix(met[8])))
met19 <- met[,10:ncol(met)]
colnames(met19)<- sub("M","X",colnames(met19))

met <- read.csv(here("2020", "2020_Tottori_Main_RootMetabolome.csv"))
rownames(met) <- paste0(substr(as.matrix(met[7]),1,2),".",sprintf("%03d",as.matrix(met[8])))
met20 <- met[,10:ncol(met)]

s_c <- colnames(met19) %in% colnames(met20)
met19<- met19[,s_c]
s_c <- colnames(met20) %in% colnames(met19)
met20<- met20[,s_c]
table(colnames(met20) == colnames(met19))

dim(met19)
dim(met20)
```

read met index

```{r}
metind<- read.csv(here("data","Metabolome_index.csv"))
metindex<- matrix(metind[,2],583,1)
rownames(metindex)<- metind[1:583,1]
```


read microbiome rarificated data
```{r}
com <- read.table(here("2018", "table-from-biom-7-2018-after.txt"), row.names = 1)
rownames(com) <- gsub(";",".",rownames(com))
com18<- com
colnames(com18) <- cbind(plot18[201:400],plot18[601:800])

com <- read.csv(here("2019", "table-from-biom-7.csv"), row.names = 1)
rownames(com) <- gsub(";",".",rownames(com))
com19<- com

com<-readRDS(here("2019", "2019_Micro_Tung.RDS"))
rownames(com)<- sub("-",".",rownames(com))
com19c<- t(com)
# comr <- read.csv(here("2019", "table-from-biom-7.csv"), row.names = 1)
# comr  <- t(comr)

com19<- com19[,colnames(com19) %in% colnames(com19c)]
com19c<- com19c[,colnames(com19c) %in% colnames(com19)]

#comriken <- read.csv(here("2020", "table-from-biom-7-2020-after.csv"))
com <- read.csv(here("2020", "2020_Tottori_Main_Microbiome_Ratio.csv"))
rownames(com) <- paste0(substr(as.matrix(com[7]),1,2),".",sprintf("%03d",as.matrix(com[8])))
com <- com[,10:ncol(com)]
com20 <- t(com)

#s_c <- rownames(com19) %in% rownames(com20)
#com19<- com19[s_c,]
#s_c <- rownames(com20) %in% rownames(com19)
#com20<- com20[s_c,]

s_c <- (rownames(com19) %in% rownames(com20)) & (rownames(com19) %in% rownames(com18))
com19<- com19[s_c,]
s_c <- rownames(com20) %in% rownames(com19)
com20<- com20[s_c,]
s_c <- rownames(com18) %in% rownames(com20)
com18<- com18[s_c,]



dim(com18)
dim(com19)
dim(com20)

```

### Condition

```{r}
CD ="W4"


if (CD == "W4"){
  print(CD)
  cd<- "Drought"
  predmet20f19 <- read.csv(here("out", "20f19_predmet_GM_blup_OneOut.csv"), row.names = 1)
  predmet19f20 <- read.csv(here("out", "19f20_predmet_GM_blup_OneOut.csv"), row.names = 1)
  
  predmet19 <- read.csv(here("out", "19f19_predmet_GM_blup_OneOut.csv"), row.names = 1)
  predmet20 <- read.csv(here("out", "20f20_predmet_GM_blup_OneOut.csv"), row.names = 1)
  
  RF <- readRDS(here("out", "19f19_predMet_RF_OneOut_W4com.rds"))
  predmet19RF<-RF[["G+Micro"]]
  
  RF2 <- readRDS(here("out", "19f20_predMet_RF_OneOut_W4com.rds"))
  predmet19f20RF<-RF2[["G+Micro"]]

  } else if (CD == "W1"){
  print(CD)
  cd<- "Control"
  predmet20f19 <- read.csv(here("out", "20f19_predmet_GM_blup_OneOut_c.csv"), row.names = 1)
  predmet19f20 <- read.csv(here("out", "19f20_predmet_GM_blup_OneOut_c.csv"), row.names = 1)
  
  predmet19 <- read.csv(here("out", "19f19_predmet_GM_blup_OneOut_c.csv"), row.names = 1)
  predmet20 <- read.csv(here("out", "20f20_predmet_GM_blup_OneOut_c.csv"), row.names = 1)
  
  RF <- readRDS(here("out", "19f19_predMet_RF_OneOut_W1com.rds"))
  predmet19RF<-RF[["G+Micro"]]
  
  RF2 <- readRDS(here("out", "19f20_predMet_RF_OneOut_W1com.rds"))
  predmet19f20RF<-RF2[["G+Micro"]]
  
  } else {
  print("error")
  }

dim(predmet19)
#RF <- readRDS(here("out", "19f19_predMet_RF_OneOut_W4snp.rds"))
#predmet19RFsnp<-RF[["G+Micro"]] 

```


select the lines which has pheno, grm, met, micro data in 2019 and 2020
```{r}
selector.grm1 <- pheno18$var.id %in% rownames(grm)
selector.com1 <-rownames(pheno18) %in% colnames(com18)

selector.grm2 <- pheno19$var.id %in% rownames(grm)
selector.com2 <-rownames(pheno19) %in% colnames(com19)

selector.grm3 <- pheno20$var.id %in% rownames(grm)
selector.com3 <-rownames(pheno20) %in% colnames(com20)


pl<- list(pheno18,pheno19,pheno20)
pl.sel<- list()

for (i in 2:3){
pheno<- pl[[i]]

if (i==1) {
  selector.grm <- selector.grm1
  selector.com <- selector.com1
}

else if (i==2) {
  selector.grm <- selector.grm2
  selector.com <- selector.com2
}

else if (i==3) {
  selector.grm <- selector.grm3
  selector.com <- selector.com3
}


pheno.sel <- pheno[selector.grm & selector.com, ]
#head(pheno.sel)
print(dim(pheno.sel))

selector.cd <- substr(rownames(pheno.sel), 1, 2) == CD 
pheno.sel.cd <- pheno.sel[selector.cd, ]
dim(pheno.sel.cd)

plot.id <- rownames(pheno.sel.cd)
rownames(pheno.sel.cd)<-pheno.sel.cd$var.id
pheno.sel.cd$var.id <- plot.id
colnames(pheno.sel.cd)[1]<- "plot.id"
sg <- rownames(grm) %in% rownames(pheno.sel.cd)
gv<-rownames(grm[sg,sg])
pheno.sel.cd<- pheno.sel.cd[gv,]
print(dim(pheno.sel.cd))
pl.sel[[i]]<- pheno.sel.cd
}

#psc18<-  pl.sel[[1]]
psc19<-  pl.sel[[2]] 
psc20<-  pl.sel[[3]]



s_p <- rownames(psc19) %in% rownames(psc20)
psc19<- psc19[s_p,]
s_p <- rownames(psc20) %in% rownames(psc19)
psc20<- psc20[s_p,]

#s_p <- colnames(psc19) %in% colnames(psc20)
#psc19<- psc19[,s_p]
#s_p <- colnames(psc20) %in% colnames(psc19)
#psc20<- psc20[,s_p]

table(rownames(psc19) == rownames(psc20))

```



2019 
```{r}
var.id <- rownames(psc19)
grm.cd <- grm[var.id, var.id]
plot.id  <- psc19$plot.id
com19.cd <- t(com19[, plot.id])
com19.cd <- scale(com19.cd[, apply(com19.cd, 2, sd) > 0])

com19c.cd <- t(com19c[, plot.id])
com19c.cd <- scale(com19c.cd[, apply(com19c.cd, 2, sd) > 0])


#met19ns.cd <- met19[plot.id, ]
met19.cd <- scale(met19[plot.id, ])
#predmet19ns<-predmet19
predmet19<-scale(predmet19)
#genome.cd<- genome[var.id,]
predmet19RF<-scale(predmet19RF)
predmet19f20RF<-scale(predmet19f20RF)

genome.cd<- genome[var.id,]
```


2020
```{r, message =F}
var.id <- rownames(psc20)
grm.cd <- grm[var.id, var.id]
plot.id  <- psc20$plot.id
com20.cd <- t(com20[, plot.id])
com20.cd <- scale(com20.cd[, apply(com20.cd, 2, sd) > 0])


#met20ns.cd <- met20[plot.id, ]
met20.cd <- scale(met20[plot.id, ])
#predmetns20<-predmet20
predmet20<-scale(predmet20)
#predmetns20f19<-predmet20f19
predmet20f19<-scale(predmet20f19)
predmet19f20<-scale(predmet19f20)
genome.cd<- genome[var.id,]

```


Integrate + RM
```{r, message =F}
psc <- rbind(psc19,psc19)

s_c <- colnames(com19.cd) %in% colnames(com20.cd)
com19.cd<- com19.cd[,s_c]
s_c <- colnames(com20.cd) %in% colnames(com19.cd)
com20.cd<- com20.cd[,s_c]

s_c <- colnames(com19.cd) %in% colnames(com20.cd)
com19.cd<- com19.cd[,s_c]
s_c <- colnames(com20.cd) %in% colnames(com19.cd)
com20.cd<- com20.cd[,s_c]

mrm19.cd <- tcrossprod(com19.cd) / ncol(com19.cd)
mrm20.cd <- tcrossprod(com20.cd) / ncol(com20.cd)

com.cd<- rbind(com19.cd,com20.cd)
rownames(com.cd)<-rownames(psc)
mrm.cd <- tcrossprod(com.cd) / ncol(com.cd)

metrm19.cd <- tcrossprod(met19.cd) / ncol(met19.cd)
metrm20.cd <- tcrossprod(met20.cd) / ncol(met20.cd)

metPrm19.cd <- tcrossprod(predmet19) / ncol(predmet19)
metPrm20.cd <- tcrossprod(predmet20) / ncol(predmet20)

metPrm20f19.cd <- tcrossprod(predmet20f19) / ncol(predmet20f19)
metPrm19f20.cd <- tcrossprod(predmet19f20) / ncol(predmet19f20)

metPrm19RF.cd <- tcrossprod(predmet19RF) / ncol(predmet19RF)
metPrm19f20RF.cd <- tcrossprod(predmet19f20RF) / ncol(predmet19f20RF)

#metns.cd <- rbind(met19ns.cd,met20ns.cd)
met.cd<- rbind(met19.cd,met20.cd)
rownames(met.cd)<-rownames(psc)
metrm.cd <- tcrossprod(met.cd) / ncol(met.cd)
```

```{R}
comn<-  paste0(rep("OTU_",ncol(com19.cd)),1:ncol(com19.cd))
comnameL <-colnames(com19.cd)
colnames(com19.cd)<- comn
```


### Yield 2019model

```{r, message =F, include=TRUE,eval=TRUE}
# K1 <- grm.cd
# K2 <- mrm19.cd
# K3 <- metrm19.cd
# K3.2<-metrm20.cd
# 
# K8 <- metPrm19.cd
# K9 <- metPrm19f20.cd
# #K10 <- RDA_M
# K11 <- metPrm19RF.cd
# K12 <- metPrm19f20RF.cd

m0  <- genome.cd #genome
m1  <- grm.cd #grm
m2  <- met19.cd #metabolome
m3  <- com19c.cd # microbiome  count
m4  <- com19.cd # microbiome rarificated
m13 <- psc19[,-1] # phenotype

print(cd)
dim(m0)
dim(m1)
dim(m2)
dim(m3)
dim(m4)
dim(m13)
#m13<-scale(m13)

```


## rn for roop LOO 
```{r}
set.seed(123)
# Define number of lambdas and the lambda sequence

n_lam <- 50
#Lambda <- exp(seq(-8, 20, length.out = n_lam))
Lambda <- exp(seq(0, 20, length.out = n_lam))


# Define X and Y sets with descriptive names
X_set <- list(m0, m2, m3, m4, cbind(m0,m4))                 # X options
X_names <- c("genome","metabolome", "microbiome","microbiome_pros","genome micro")  # Descriptive X names
Y_set <- list(m13)       # Y options
Y_names <- c("phenotype")  # Descriptive Y names

ni<-c(5)
nj<-c(1)

# Loop over all combinations of X and Y

cmat<- matrix(NA,length(ni),ncol(m13))
colnames(cmat)<-colnames(m13)
rownames(cmat)<-X_names[ni]
for (k in 1:length(ni) ){
 
    i<-ni[k]
    j<-nj[k]
    
    X <- X_set[[i]]  # Select X
    Y <- Y_set[[j]]  # Select Y
    
    # Convert X and Y to matrix format
    X <- as.matrix(X)
    Y <- as.matrix(Y)
    
    pred_Yall<-matrix(NA,nrow(Y),ncol(Y))
    
    pb <- txtProgressBar(min = 0, max =nrow(X) , style = 3)
    for (rn in 1: nrow(X)){
    #for (rn in 1: 2){
        X_train<-X[-rn,]
        X_test<-X[rn,,drop=F]
        Y_train<-Y[-rn,]
        Y_test<-Y[rn,,drop=F]
        
        # Perform cross-validation using rrda
        #sink("/dev/null")
        plan(multisession)
        #tic()
        cv_result <- rrda.cv(X = X_train, Y = Y_train,lambda = Lambda,maxrank = 9,verbose = F)
        #toc()
        plan(sequential)
        #sink()
        # Extract optimal lambda and rank
        L <- cv_result$opt_min$lambda
        K <- cv_result$opt_min$rank
        
        # Fit the model using the optimal lambda and rank
        b <- rrda.fit(Y = Y_train, X = X_train, lambda = L, nrank = K)
        
        # Predict Y using the fitted model
        pred_Y <- rrda.predict(b, X_test, lambda = L, nrank = K)[[1]][[1]][[1]]
        pred_Yall[rn,]<- pred_Y
        setTxtProgressBar(pb, rn)
        }
        close(pb)
        
    PY<-list(pred_Yall=pred_Yall,Y=Y)
    #saveRDS(PY,paste0("/Users/hayatoyoshioka/Documents/R/HayatoINRAE/out/Soy/",cd,"/Pred_X=", X_names[i], "Y=", Y_names[j],cd,"gm2019_LOO.RDS"))
    Y <- PY$Y
    pred_Y <- PY$pred_Yall

    cor<-diag(cor(Y,pred_Y))
    cmat[k,]<-cor
}
saveRDS(cmat,paste0("/Users/hayatoyoshioka/Documents/R/HayatoINRAE/out/Soy/",cd,"cor_gm2019_LOO_test_2.RDS"))

    
```


```{R,fig.dim = c(8, 4)}
pred.all<-readRDS(paste0("/Users/hayatoyoshioka/Documents/R/HayatoINRAE/out/Soy/",cd,"cor_gm2019_LOO.RDS"))
#model.name <- c("G","Met","Micro","Micro_proc","G + Micro")
model.name <- c("G","Met","Micro","G + Micro")

pred.all2<-readRDS(paste0("/Users/hayatoyoshioka/Documents/R/HayatoINRAE/out/Soy/",cd,"cor_gm2019_LOOg16.RDS"))


pred.all[1,]<-pred.all2[1,]
pred.all[5,]<-pred.all2[2,]
pred.all<-pred.all[-4,]
trait.name <- colnames(pred.all) %>% sort() #sort
pred.all<- data.frame(pred.all) %>% select(trait.name)
df.all <- NULL


for(i in 1:length(trait.name)) {
  
  pred <-  pred.all[,i]
  df <- data.frame(trait = trait.name[i],model = model.name, mean = pred)
  df.all <- rbind(df.all, df)
}

df.all[df.all < 0] <- 0
df.all$model <- factor(df.all$model, levels = model.name)
df.all$trait <- factor(df.all$trait)
levels(df.all$trait) <- colnames(pred.all)
g <- ggplot(df.all)
g <- g + geom_bar(aes(x = trait, y = mean, fill = model), 
                  stat = "identity",  position = "dodge")  
g <- g + ggtitle(paste0("Yield Prediction ridge RDA in 2019 ",cd))
g <- g + ylab("COR")
g <- g + xlab("")
g <- g + ylim(0,0.90)

g <- g + theme(axis.text.x = element_text(angle = 60, hjust=1))

print(g)

```


# result plot (old)
```{R,fig.dim = c(8, 4)}
#p<- c("KZ1KZ2KZ3KZ8KZ9KZ11KZ1_2KZ1_2_8KZ1_2_9KZ1_2_11KZ1_2_12KZ1_2_3")
#pred.all<-resultEachModel
#pred.all <- read.csv(here("out",paste0("2019_blup",p,"_OneOut_",CD,".csv")),row.names=1)
res<-readRDS(here("out", paste0("yPredYield_BLUPwRF_", CD, "com.RDS")))
p<-res$p
pred.all<-res$resultEachModel

model.name <- c("G","Micro","TrueMet","PredMetBlupf19","PredMetBlupf20","PredMetRFf19","G+Micro","G+Micro+PredMetBLUP","G+Micro+PredMetBLUPf20","G+Micro+PredMetRF_f19","G+Micro+PredMetRF_f20","G+Micro+TrueMet")

trait.name <- colnames(pred.all) %>% sort() #sort
pred.all<- data.frame(pred.all) %>% select(trait.name)
df.all <- NULL


for(i in 1:length(trait.name)) {
  
  pred <-  pred.all[,i]
  df <- data.frame(trait = trait.name[i],model = model.name, mean = pred)
  df.all <- rbind(df.all, df)
}

df.all[df.all < 0] <- 0
df.all$model <- factor(df.all$model, levels = model.name)
df.all$trait <- factor(df.all$trait)
levels(df.all$trait) <- colnames(pred.all)
g <- ggplot(df.all)
g <- g + geom_bar(aes(x = trait, y = mean, fill = model), 
                  stat = "identity",  position = "dodge")  
g <- g + ggtitle(paste0("Yield Prediction BLUP in 2019 ",cd))
g <- g + ylab("COR")
g <- g + xlab("")
g <- g + ylim(0,0.9)
g <- g + theme(axis.text.x = element_text(angle = 60, hjust=1))

print(g)

```

```{r}
res<-readRDS(here("out", paste0("yPredYield_BLUPwRF_", CD, "com.RDS")))
p<-res$p
pred.all<-res$resultEachModel

pred.all<- pred.all[c(1,3,2,7,10),]

model.name <- c("G","Met","Micro","G+Micro","G+Micro+PredMetRF")

rda<-readRDS(paste0("/Users/hayatoyoshioka/Documents/R/HayatoINRAE/out/Soy/",cd,"cor_gm2019_LOO.RDS"))
rda5_1<-rda[5,]
rda5<-rda[5,]

rda<-readRDS(paste0("/Users/hayatoyoshioka/Documents/R/HayatoINRAE/out/Soy/",cd,"cor_gm2019_LOO_test.RDS"))
rda5_2<-rda[2,]

pred.all<-rbind(pred.all,rda5_2)


model.name <- c("G (BLUP)","Met (BLUP)","Micro (BLUP)","G+Micro (BLUP)","G+Micro+PredMetRF (BLUP)","G+Micro (ridge RDA)")


trait.name <- colnames(pred.all) %>% sort() #sort
pred.all<- data.frame(pred.all) %>% select(trait.name)
df.all <- NULL


for(i in 1:length(trait.name)) {
  
  pred <-  pred.all[,i]
  df <- data.frame(trait = trait.name[i],model = model.name, mean = pred)
  df.all <- rbind(df.all, df)
}

df.all[df.all < 0] <- 0
df.all$model <- factor(df.all$model, levels = model.name)
df.all$trait <- factor(df.all$trait)
levels(df.all$trait) <- colnames(pred.all)
g <- ggplot(df.all)
g <- g + geom_bar(aes(x = trait, y = mean, fill = model), 
                  stat = "identity",  position = "dodge")  
g <- g + ggtitle(paste0("Yield Prediction in 2019 ",cd))
g <- g + ylim(0,0.90)
g <- g + ylab("COR")
g <- g + xlab("")

g <- g + theme(axis.text.x = element_text(angle = 60, hjust=1))

print(g)
```

