---
title: "75_BLUP_samedata"
author: "Hayato Yoshioka"
date: "2025-01-29"
output: html_document
---

reference 59

Met prediction
New micro data

```{r, message =F}
require(BGLR)
library(dplyr)
require(here)
require(ggplot2)
# require(reshape2)
# require(gridExtra)
# library(readr)
library(stringr)
# library(ggsci)
library(RAINBOWR)
# library(lubridate)
library(foreach)
library(future)
library(doFuture)
# library(doRNG)
library(tictoc)
library(doSNOW)
library(purrr)
source("Script/MyFunctions.R")
# library(vegan)
# library(VARshrink)
# library(ggplot2)
# library(glmnet)
# library(lars)
require(ranger)
# require(ggrepel)
# require(tidyverse)
library(rrda)

getwd()
```

seed
```{r, message =F}
# save or read the seed
seedIndCsv <-  here("out","seedInd.csv")
if (file.exists(seedIndCsv)) {
  seedInd <- read.csv(seedIndCsv, row.names = 1, header = T)
  seedInd <- c(as.matrix(seedInd))
} else {
  seedInd <- sample(1:500, 10, replace = F)
  write.csv(x = seedInd, file =  here("out","seedInd.csv"))
}
```

```{r}
Data<-readRDS(here("data/two/two2019.RDS"))
#predmet<-readRDS(here("out","Soy",cd,"predmmet_gmicro_rda.RDS"))

genome<-Data$genome3k
grm<-Data$grm
met<-Data$met
mic<-Data$mic
mir<-Data$mir
pheno<-Data$pheno

cd<-Data$cd

if (cd == "Drought"){
	CD<-"W4"
} else if (cd=="Control"){
	CD<-"W1"
}

RF <- readRDS(here("out", "19f19_predMet_RF_OneOut_W4com.rds"))
predmet19RF<-RF[["G+Micro"]]

#predmet19RDA<-readRDS(here("out","Soy",cd,"predmmet_gmicro_rda.RDS"))

```


RM
```{r, message =F}
psc19<-cbind(rownames(grm),pheno)
# grm.cd<-grm
# mrm19r.cd <- tcrossprod(mir) / ncol(mir)
# mrm19c.cd <- tcrossprod(mic) / ncol(mic)
# metrm19.cd <- tcrossprod(met) / ncol(met)
# metPrm19RF.cd <- tcrossprod(predmet19RF) / ncol(predmet19RF)
```

### Yield 2019model

```{, message =F, include=TRUE,eval=TRUE}
K1 <- grm.cd

K2.1 <- mrm19r.cd
K2.2 <- mrm19c.cd

K3 <- metrm19.cd


K11 <- metPrm19RF.cd

#K13 <- metPrm19RDA.cd 

	
Z <- design.Z(pheno.labels = rownames(grm.cd),geno.names = rownames(grm.cd))

KZ1<- list(A= list(K = K1, Z = Z))

KZ2.1<- list(A= list(K = K2.1, Z = Z))
KZ2.2<- list(A= list(K = K2.2, Z = Z))

KZ1_2.1<- list(A= list(K = K1, Z = Z),B= list(K = K2.1, Z = Z))
KZ1_2.2<- list(A= list(K = K1, Z = Z),B= list(K = K2.2, Z = Z))


ZETAlist <- list(KZ1_2.1,KZ1_2.2)
names(ZETAlist) <- c("KZ2.2","KZ1_2.2")
names<- names(ZETAlist)

```

```{}
y <- psc19 # 36min
tic()
res<- getBLUP_simple(ZETAlist,y)
toc()
saveRDS(res, here("out", paste0("yPredYield_BLUP_micro_gmicro_count_", CD, "com.RDS")))

#aa<-readRDS(here("out", paste0("yPredYield_BLUPcountrarificated_", CD, "com.RDS")))

res$resultEachModel
```



Define function for RF
```{r}
cvRF <- function(y, X) {
  dat <- data.frame(y, X)
  y.pred <- matrix(NA, nrow = length(y), ncol = 1)
  
    for(j in 1:nrow(y.pred)) {
      
      
      dat.train <- dat[-j, ]
      dat.test <- dat[j, ]
      
      model <- ranger(y ~ ., data = dat.train)
      model.pred <- predict(model, data = dat.test)
      y.pred[j, 1] <- model.pred$predictions 
  }
  #print(cor(dat$y, y.pred))
  y.pred
}
```


Define function for RF2
```{r}
cvRF2 <- function(y, y2, X, X2) {
  dat <- data.frame(y, X)
  y.pred <- matrix(NA, nrow = length(y), ncol = 1)
  dat2 <- data.frame(y2, X2)
  colnames(dat2) <- colnames(dat)
  y.pred2 <- matrix(NA, nrow = length(y2), ncol = 1)
  
    for(j in 1:nrow(y.pred)) {
 
      dat.train <- dat[-j, ]
      dat.test <- dat[j, ]
      dat.train2 <- dat2[-j, ]
      dat.test2 <- dat2[j, ]
      
      model <- ranger(y ~ ., data = dat.train2)
      model.pred <- predict(model, data = dat.test)
      y.pred[j, 1] <- model.pred$predictions 
  }
  #print(cor(dat$y, y.pred))
  y.pred
}
```

### 19 in 19 Model

```{R,eval = TRUE}
K1 <- grm.cd
K2 <- mic
```

### DO pararel
```{R,eval = TRUE}

Y <- met[,c(1:2)]


iterations=ncol(Y)

cl <- makeCluster(6)
registerDoSNOW(cl)
pb <- txtProgressBar(max = iterations, style = 3)
progress <- function(n) setTxtProgressBar(pb, n)
opts <- list(progress = progress)

tic()
y.pred.list<- foreach(i = 1:iterations,.options.snow = opts,.export = "ranger") %dopar% {

#for(i in 1:2) {
  trait.name <- colnames(Y)[i]
  print(paste(i, "/", ncol(Y), trait.name))

  y <- Y[, i]
  y.pred.all <- y

  # # G model
  # X <- K1
  # y.pred <- cvRF(y, X)
  # r.g <- cor(y, y.pred)[1,]
  # print(r.g)
  # colnames(y.pred) <- paste0("G", "_cv1")
  # y.pred.all <- cbind(y.pred.all, y.pred)
  # 
  # # M model
  # X <- K2
  # y.pred <- cvRF(y, X)
  # r.g <- cor(y, y.pred)[1,]
  # print(r.g)
  # colnames(y.pred) <- paste0("M", "_cv1")
  # y.pred.all <- cbind(y.pred.all, y.pred)

  # G * M model
  X <- cbind(K1,K2)
  y.pred <- cvRF(y, X)
  r.g <- cor(y, y.pred)[1,]
  print(r.g)
  colnames(y.pred) <- paste0("GM", "_cv1")
  y.pred.all <- cbind(y.pred.all, y.pred)

  # save data
  print(cor(y.pred.all)[1,])
  rownames(y.pred.all) <- rownames(psc19)
  colnames(y.pred.all)[1] <- "y.obs"
  #write.csv(y.pred.all, here("out", paste0("yPred_", trait.name, "_D.csv")))
  return(y.pred.all) 
}
close(pb)
stopCluster(cl) 
toc()

names(y.pred.list) <- colnames(Y)
saveRDS(y.pred.list, here("out", paste0("yPredMet_RF_countmicro_", "W4", ".RDS")))
```


```{r}

set<- readRDS(here("out", paste0("yPredMet_RF_countmicro2_W4.RDS")))
#yPredMet_RF<- readRDS("~/Documents/R/HayatoINRAE/out/yPredMet_RF_countmicro_W4.RDS")
pred <- vector("list", 2)
names(pred) <- c("G+Micro", "obs")
for(i in 1:length(set)) {
  dat <- set[[i]]
  for(j in 1) {
    pred[[j]] <- cbind(pred[[j]], dat[,j + 1])
  }
  pred[[2]] <- 
    cbind(pred[[2]], dat[, 1])
}
for(i in 1:2) {
  rownames(pred[[i]]) <- rownames(set[[1]])
  colnames(pred[[i]]) <- names(set)
}

saveRDS(pred, here("out", paste0("19f19_predMet_RF_countmicro2", "_W4", ".RDS")))
```



