


```{r,message=F,include=FALSE,echo=FALSE}
library(purrr)
library(stringr)
library(dplyr)
library(corrplot)
source("Script/MyFunctions.R")
library(RAINBOWR)
library(DiagrammeR)
library(tictoc)
library(doSNOW)
library(ranger)
library(here)
library(psych)
library(doFuture)
library(MASS)
library(rrBLUP)
require(ranger)
library(doSNOW)
#library(sigmoid)
```




run
```{r}
# Setup before loop
set.seed(123)
n <- 30
a <- 10
b <- 10
c <- 10
d <- 10
ws<- -1
w <- 1

#for(model in c("sigmoid","linear")){
#for(model in c("tanh")){
for(model in c("sigmoid","p2","relu","linear")){
#for(model in c("p2","relu","linear")){
print(model)
base_fol <- "out/TSS/ite_BLUP/"
dir.create(base_fol, showWarnings = FALSE, recursive = TRUE)
# Assuming folder creation is required only once
cv<-c()
cvv<-c()
# Loop over 100 iterations
for (iteration in 91:100) {
 print(iteration)
  fol <- paste0(base_fol, "TSS_",model,"_nabcd_iter", iteration, "_", n, a, b, c, d)
  
  # Ensure directories for each iteration
  dir.create(fol, showWarnings = FALSE, recursive = TRUE)
  dir.create(paste0(fol, "/pdf"), showWarnings = FALSE, recursive = TRUE)

  data <- simdata5(n=n, a=a, b=b, c=c, d=d, ws=ws, w=w, model=model,noise=0.1)
  
  A <- data$A
  B <- data$B
  C <- data$C
  D <- data$D
  
  
  Z<-diag(n)
  
  bt <-function(M){
    K<-tcrossprod(M) / ncol(M)
    return(K)
  }
  
  KZA<- list(A= list(K = bt(A), Z = Z))
  #KZB<- list(A= list(K = bt(B), Z = Z))
  #KZC<- list(A= list(K = bt(C), Z = Z))
  #KZD<- list(A= list(K = bt(D), Z = Z))
  
  # Prediction and saving results
  ZETAlist <- list(A=KZA)
  names(ZETAlist)<-c("KZA")
  
  Y <- B
  
  res<- getBLUP_simulation(ZETAlist,Y)
  #res <- getRF(RFlist, Y)
  
  saveRDS(res, paste0(fol, "/resb_a"))
  
  # Generate boxplot for this iteration
  file_path <- paste0(fol,"/pdf/boxplot_iteration_", iteration, ".pdf")
  pdf(file = file_path, width = 8, height = 5)
  boxplot(t(res$resultEachModel), main=paste("Bpred fitting by - Iteration", iteration))
  dev.off()
  
  # Bpred <- matrix(NA, nrow = nrow(Y), ncol = ncol(Y))
  # for (i in 1:ncol(Y)) {
  #   Bpred[,i] <- res$y.pred.list[[i]][,"A"]
  # }
  
  Bpred <- res$predictDataList[[1]]
  
  saveRDS(Bpred, paste0(fol, "/Bpred_A"))
  
  Bpred<- readRDS(paste0(fol,"/","Bpred_A"))

  # AB  <- list(A=A,B=B)
  # ABpred <- list(A=A, Bpred=Bpred)
  # RFlist <- list(A=list(A=A),ABpred=ABpred)

  KZABpred<- list(A= list(K = bt(A), Z = Z),Bpred= list(K = bt(Bpred), Z = Z))

  ZETAlist <- list(A=KZA,ABpred=KZABpred)
  Y <- C

  res <- getBLUP_simulation(ZETAlist,Y)

  saveRDS(res,paste0(fol,"/","res_abpred"))
  res<- readRDS(paste0(fol,"/","res_abpred"))
  
  # Generate additional plots
  file_path <- paste0(fol, "/pdf/boxplot4ab_2_iter_", iteration, ".pdf")
  pdf(file = file_path, width = 5, height = 5)
  boxplot(t(res$resultEachModel), main=paste("C Prediction by - Iteration", iteration), ylim=c(0,0.8))
  dev.off()
  
  cor10<-t(res$resultEachModel)
  cvv<-rbind(cvv,cor10)
  corm<-rowMeans(res$resultEachModel)
  cv<-rbind(cv,corm)
}

saveRDS(cvv,paste0(base_fol,"/",model,"cor10"))
saveRDS(cv,paste0(base_fol,"/",model,"corm"))

cvv<-readRDS(paste0(base_fol,"/",model,"cor10"))
cv <-readRDS(paste0(base_fol,"/",model,"corm"))

max_cv <- max(cv, na.rm = TRUE)
min_cv <- min(cv, na.rm = TRUE)
# Create the plot using the max and min for x and y limits
plot(cv, xlim = c(min_cv, max_cv), ylim = c(min_cv, max_cv), 
     main = model, xlab = "A", ylab = "ABpred")

# Add the 45-degree line
abline(0, 1, col = "red")

max_cvv <- max(cvv, na.rm = TRUE)
min_cvv <- min(cvv, na.rm = TRUE)

# Create the plot using the max and min for x and y limits
plot(cvv, xlim = c(min_cvv, max_cvv), ylim = c(min_cvv, max_cvv), 
     main = model, xlab = "A", ylab = "ABpred")

# Add the 45-degree line
abline(0, 1, col = "red")

boxplot(cv)
boxplot(cvv)

 
}


```



# plot
```{r, fig.width=5, fig.height=5}
n <- 30
a <- 10
b <- 10
c <- 10
d <- 10
ws<- -1
w <- 1

#for(model in c("sigmoid","p2","relu","binary")){

for(model in c("sigmoid","p2","relu","linear")){
# Create directories if they don't exist
base_fol <- "out/TSS/ite_BLUP/"
dir.create(base_fol, showWarnings = FALSE, recursive = TRUE)
# Assuming folder creation is required only once
cv<-c()
cvv<-c()
# # Loop over 100 iterations
# for (iteration in 1:100) {
#  #print(iteration)
#   fol <- paste0(base_fol, "TSS_",model,"_nabcd_iter", iteration, "_", n, a, b, c, d)
#   
#   # Ensure directories for each iteration
#   dir.create(fol, showWarnings = FALSE, recursive = TRUE)
#   dir.create(paste0(fol, "/pdf"), showWarnings = FALSE, recursive = TRUE)
# 
#   Bpred<- readRDS(paste0(fol,"/","Bpred_A"))
# 
#   res<- readRDS(paste0(fol,"/","res_abpred"))
# 
#   cor10<-t(res$resultEachModel)
#   cvv<-rbind(cvv,cor10)
#   corm<-rowMeans(res$resultEachModel)
#   cv<-rbind(cv,corm)
# }
# 
# saveRDS(cvv,paste0(base_fol,"/",model,"cor10"))
# saveRDS(cv,paste0(base_fol,"/",model,"corm"))

cvv<-readRDS(paste0(base_fol,"/",model,"cor10"))
cv <-readRDS(paste0(base_fol,"/",model,"corm"))
 
# 
# max_cv <- max(cv, na.rm = TRUE)
# min_cv <- min(cv, na.rm = TRUE)

if (model %in% c("sigmoid", "p2")) {
    max_cv <- 0.3
    min_cv <- -0.1
} else if (model %in% c("relu")) {
    max_cv <- 0.5
    min_cv <- 0.1
  } else if (model %in% c("linear")) {
    max_cv <- 0.8
    min_cv <- 0.4
  }

if(model=="p2"){
 model="square"
}

max_cv <-  1
min_cv <- -1

# # Create the plot using the max and min for x and y limits
plot(cv, xlim = c(min_cv, max_cv), ylim = c(min_cv, max_cv),
     main = paste0("BLUP : ",model),ylab="Trained by A + Bpred", xlab="Trained by A")

# Add the 45-degree line
abline(0, 1, col = "red")

max_cvv <-  1
min_cvv <- -1

print(model)
print(table((cv[,1]-cv[,2]) < 0))
print(table((cvv[,1]-cvv[,2]) < 0))
# Create the plot using the max and min for x and y limits
plot(cvv, xlim = c(min_cvv, max_cvv), ylim = c(min_cvv, max_cvv), 
     main = paste0("BLUP : ",model),ylab="Trained by A + Bpred", xlab="Trained by A",
     cex=0.8
     #, xlab = "A", ylab = "ABpred"
     )

# Add the 45-degree line
abline(0, 1, col = "red")
boxplot(cv,ylim=c(min_cv, max_cv), 
     main = paste0("model : ",model))
boxplot(cvv,ylim=c(min_cvv, max_cvv), 
     main = paste0("model : ",model))
}


```

# plot
```{r, fig.width=5, fig.height=5}
n <- 50
a <- 10
b <- 10
c <- 10
d <- 10
ws<- -1
w <- 1

#for(model in c("sigmoid","p2","relu","binary")){

for(model in c("sigmoid","p2","relu","linear")){
# Create directories if they don't exist
base_fol <- "out/TSS/ite_BLUP/"
dir.create(base_fol, showWarnings = FALSE, recursive = TRUE)
# Assuming folder creation is required only once
cv<-c()
cvv<-c()
# Loop over 100 iterations
for (iteration in 1:100) {
 #print(iteration)
  fol <- paste0(base_fol, "TSS_",model,"_nabcd_iter", iteration, "_", n, a, b, c, d)
  
  # Ensure directories for each iteration
  dir.create(fol, showWarnings = FALSE, recursive = TRUE)
  dir.create(paste0(fol, "/pdf"), showWarnings = FALSE, recursive = TRUE)

  Bpred<- readRDS(paste0(fol,"/","Bpred_A"))

  res<- readRDS(paste0(fol,"/","res_abpred"))

  cor10<-t(res$resultEachModel)
  cvv<-rbind(cvv,cor10)
  corm<-rowMeans(res$resultEachModel)
  cv<-rbind(cv,corm)
}

saveRDS(cvv,paste0(base_fol,"/",model,"cor10"))
saveRDS(cv,paste0(base_fol,"/",model,"corm"))

cvv<-readRDS(paste0(base_fol,"/",model,"cor10"))
cv <-readRDS(paste0(base_fol,"/",model,"corm"))
 
# 
# max_cv <- max(cv, na.rm = TRUE)
# min_cv <- min(cv, na.rm = TRUE)

if (model %in% c("sigmoid", "p2")) {
    max_cv <- 0.3
    min_cv <- -0.1
} else if (model %in% c("relu")) {
    max_cv <- 0.5
    min_cv <- 0.1
  } else if (model %in% c("linear")) {
    max_cv <- 0.8
    min_cv <- 0.4
  }

if(model=="p2"){
 model="square"
}

max_cv <-  1
min_cv <- -1

# # Create the plot using the max and min for x and y limits
plot(cv, xlim = c(min_cv, max_cv), ylim = c(min_cv, max_cv),
     main = paste0("model : ",model),ylab="Trained by A + Bpred", xlab="Trained by A")

# Add the 45-degree line
abline(0, 1, col = "red")

max_cvv <-  1
min_cvv <- -1

print(model)
print(table((cv[,1]-cv[,2]) < 0))
print(table((cvv[,1]-cvv[,2]) < 0))
# Create the plot using the max and min for x and y limits
plot(cvv, xlim = c(min_cvv, max_cvv), ylim = c(min_cvv, max_cvv), 
     main = paste0("BLUP : ",model),ylab="Trained by A + Bpred", xlab="Trained by A",
     cex=1
     #, xlab = "A", ylab = "ABpred"
     )

# Add the 45-degree line
abline(0, 1, col = "red")
boxplot(cv,ylim=c(min_cv, max_cv), 
     main = paste0("model : ",model))
boxplot(cvv,ylim=c(min_cvv, max_cvv), 
     main = paste0("model : ",model))
}


```