
BLUP

```{r,message=F,include=FALSE,echo=FALSE}
library(purrr)
library(stringr)
library(dplyr)
library(corrplot)
source("Script/MyFunctions.R")
library(RAINBOWR)
library(DiagrammeR)
library(tictoc)
library(doSNOW)
library(ranger)
library(here)
library(psych)
library(doFuture)
library(MASS)
library(rrBLUP)
require(ranger)
library(doSNOW)
#library(sigmoid)


```


run
```{r, fig.width=5, fig.height=5}
# Setup before loop
set.seed(120)
n <- 30
a <- 10
b <- 10
c <- 10
d <- 10
e <- 1
ws<- -1
w <- 1

#for(model in c("sigmoid","linear")){
#for(model in c("tanh")){
for(model in c("sigmoid","p2","relu","linear")){
#for(model in c("exp")){
#for(model in c("sigmoid")){
  #for(model in c("tanh")){
#for(model in c("linear")){
#for(model in c("p2","relu","linear")){
print(model)
# Create directories if they don't exist
base_fol <- "out/TSS/ite_abpred/BLUP120/"
dir.create(base_fol, showWarnings = FALSE, recursive = TRUE)
# Assuming folder creation is required only once
cv<-c()
cvv<-c()
# Loop over 100 iterations
for (iteration in 1:10) {
 print(iteration)
  fol <- paste0(base_fol, "TSS_",model,"_nabcd_iter", iteration, "_", n, a, b, c, d, e)
  
  # Ensure directories for each iteration
  dir.create(fol, showWarnings = FALSE, recursive = TRUE)
  dir.create(paste0(fol, "/pdf"), showWarnings = FALSE, recursive = TRUE)

  data <- simdata4(n=n, a=a, b=b, c=c, d=d, ws=ws, w=w, model=model,noise=e)
  
  A <- data$A
  B <- data$B
  C <- data$C
  D <- data$D
  
  
  Z<-diag(n)
  
  KZA<- list(A= list(K = bt(A), Z = Z))
  #KZB<- list(A= list(K = bt(B), Z = Z))
  #KZC<- list(A= list(K = bt(C), Z = Z))
  #KZD<- list(A= list(K = bt(D), Z = Z))
  
  # Prediction and saving results
  ZETAlist <- list(A=KZA)
  names(ZETAlist)<-c("KZA")
  
  Y <- B
  
  res<- getBLUP_simulation(ZETAlist,Y)
  
  #saveRDS(res, paste0(fol, "/resb_a"))
  

  
  # Bpred <- matrix(NA, nrow = nrow(Y), ncol = ncol(Y))
  # for (i in 1:ncol(Y)) {
  #   Bpred[,i] <- res$y.pred.list[[i]][,"A"]
  # }
  
  Bpred <- res$predictDataList[[1]]
  
  saveRDS(Bpred, paste0(fol, "/Bpred_A"))
  #base_fol <- "out/TSS/ite_abpred/BLUP120/"
  #fol <- paste0(base_fol, "TSS_",model,"_nabcd_iter", iteration, "_", n, a, b, c, d, e)
  
  #Bpred<- readRDS(paste0(fol,"/","Bpred_A"))
  
  #base_fol <- "out/TSS/ite_abpred/BLUP120/"
  #fol <- paste0(base_fol, "TSS_",model,"_nabcd_iter", iteration, "_", n, a, b, c, d, e)
  
  KZABpred<- list(A= list(K = bt(A), Z = Z),Bpred= list(K = bt(Bpred), Z = Z))

  ZETAlist <- list(ABpred=KZABpred)
  
  Y <- C

  res <- getBLUP_simulation(ZETAlist,Y)

  saveRDS(res,paste0(fol,"/","res_abpred"))
  res<- readRDS(paste0(fol,"/","res_abpred"))
  
  
  res2 <- getBLUP_ab(ZETAlist,Y,B = B,Bpred = Bpred)
  
  saveRDS(res2,paste0(fol,"/","res_abpred_b"))
  res2<- readRDS(paste0(fol,"/","res_abpred_b"))
  #saveRDS(res2,paste0(fol,"/","res_abpred_b"))
  
  res12_all<- rbind(data.frame(res2$resultEachModel),data.frame(res$resultEachModel))
  
  rownames(res12_all)<-c("ABpred_AB","ABpred")
  
  cor10<-t(res12_all)
  cvv<-rbind(cvv,cor10)
  corm<-rowMeans(res12_all)
  cv<-rbind(cv,corm)
}


saveRDS(cvv,paste0(base_fol,"/",model,"cor10"))
saveRDS(cv,paste0(base_fol,"/",model,"corm"))

cvv<-readRDS(paste0(base_fol,"/",model,"cor10"))
cv <-readRDS(paste0(base_fol,"/",model,"corm"))

max_cv <- 1
min_cv <- -1
# Create the plot using the max and min for x and y limits
plot(cv, xlim = c(min_cv, max_cv), ylim = c(min_cv, max_cv), 
     main = model)

# Add the 45-degree line
abline(0, 1, col = "red")

max_cvv <- 1
min_cvv <- -1

# Create the plot using the max and min for x and y limits
plot(cvv, xlim = c(min_cvv, max_cvv), ylim = c(min_cvv, max_cvv), 
     main = model)

# Add the 45-degree line
abline(0, 1, col = "red")

boxplot(cv)
#boxplot(cvv)

 
}


```




# plot make
```{r, fig.width=5, fig.height=5}
n <- 30
a <- 10
b <- 10
c <- 10
d <- 10
e <- 1
e<-1
ws<- -1
w <- 1

#for(model in c("sigmoid","p2","relu","binary")){

par(pty="s")
for(model in c("sigmoid","p2","relu","linear")){
#for(model in c("sigmoid")){
# Create directories if they don't exist
base_fol <- "out/TSS/ite_abpred/BLUP120/"
dir.create(base_fol, showWarnings = FALSE, recursive = TRUE)
# Assuming folder creation is required only once
cv<-c()
cvv<-c()
# Loop over 100 iterations
for (iteration in 1:100) {
 #print(iteration)
  fol <- paste0(base_fol, "TSS_",model,"_nabcd_iter", iteration, "_", n, a, b, c, d, e)
  
  # Ensure directories for each iteration
  dir.create(fol, showWarnings = FALSE, recursive = TRUE)
  dir.create(paste0(fol, "/pdf"), showWarnings = FALSE, recursive = TRUE)

  #Bpred<- readRDS(paste0(fol,"/","Bpred_A"))

  res<- readRDS(paste0(fol,"/","res_abpred"))

  res2<-readRDS(paste0(fol,"/","res_abpred_b"))
  
  res12_all<- rbind(data.frame(res2$resultEachModel),data.frame(res$resultEachModel))
  
  rownames(res12_all)<-c("ABpred_AB","ABpred")
  
  
  cor10<-t(res12_all)
  cvv<-rbind(cvv,cor10)
  corm<-rowMeans(res12_all)
  cv<-rbind(cv,corm)
}

saveRDS(cvv,paste0(base_fol,"/",model,"cor10"))
saveRDS(cv,paste0(base_fol,"/",model,"corm"))

cvv<-readRDS(paste0(base_fol,"/",model,"cor10"))
cv <-readRDS(paste0(base_fol,"/",model,"corm"))
 

# max_cv <- max(cv, na.rm = TRUE)
# min_cv <- min(cv, na.rm = TRUE)



if(model=="p2"){
 model="square"
}
max_cv <- 1
min_cv <- -1

# # Create the plot using the max and min for x and y limits
p<-plot(cv, xlim = c(min_cv, max_cv), ylim = c(min_cv, max_cv),
     main = paste0("BLUP : ",model),ylab="Trained by A + Bpred", xlab="Trained by A + B")

# Add the 45-degree line
p<- p + abline(0, 1, col = "red")
print(p)

max_cvv <-  1
min_cvv <- -1

print(model)
print(table((cv[,1]-cv[,2]) < 0))
print(table((cvv[,1]-cvv[,2]) < 0))
# Create the plot using the max and min for x and y limits
p2<-plot(cvv, xlim = c(min_cvv, max_cvv), ylim = c(min_cvv, max_cvv), 
     main = paste0("BLUP-BLUP : ",model),ylab="Trained by A + Bpred", xlab="Trained by A + B",
     cex=1
     #, xlab = "A", ylab = "ABpred"
     )

# Add the 45-degree line
p2<-p2+abline(0, 1, col = "red")
print(p2)

}

par()


#saveRDS(cv,here)

```

```{r, fig.width=8, fig.height=8}
# 2×2のレイアウトを設定
par(mfrow = c(2, 2),pty="s")

for (model in c("linear", "relu", "p2", "sigmoid")) {
  base_fol <- "out/TSS/ite_abpred/BLUP120/"
  #dir.create(base_fol, showWarnings = FALSE, recursive = TRUE)

  cv <- c()
  cvv <- c()
  
  for (iteration in 1:100) {
    fol <- paste0(base_fol, "TSS_", model, "_nabcd_iter", iteration, "_", n, a, b, c, d, e)
    
    #dir.create(fol, showWarnings = FALSE, recursive = TRUE)
    #dir.create(paste0(fol, "/pdf"), showWarnings = FALSE, recursive = TRUE)

    res <- readRDS(paste0(fol, "/res_abpred"))
    res2 <- readRDS(paste0(fol, "/res_abpred_b"))
    
    res12_all <- rbind(data.frame(res2$resultEachModel), data.frame(res$resultEachModel))
    rownames(res12_all) <- c("ABpred_AB", "ABpred")
    
    cor10 <- t(res12_all)
    cvv <- rbind(cvv, cor10)
    corm <- rowMeans(res12_all)
    cv <- rbind(cv, corm)
  }

  saveRDS(cvv, paste0(base_fol, "/", model, "cor10"))
  saveRDS(cv, paste0(base_fol, "/", model, "corm"))

  cvv <- readRDS(paste0(base_fol, "/", model, "cor10"))
  cv <- readRDS(paste0(base_fol, "/", model, "corm"))

  if (model == "p2") {
    model <- "square"
  }

  max_cvv <- 1
  min_cvv <- -1

  # p2プロット
  plot(cvv, xlim = c(min_cvv, max_cvv), ylim = c(min_cvv, max_cvv), 
       main = paste0("BLUP-BLUP : ", model), 
       ylab = "Trained by A + Bpred", xlab = "Trained by A + B",
       cex = 1)
  
  abline(0, 1, col = "red")
}

# レイアウトを元に戻す
par(mfrow = c(1, 1))

```


# plot from cv
```{, fig.width=5, fig.height=5}
n <- 30
a <- 10
b <- 10
c <- 10
d <- 10
ws<- -1
w <- 1

#for(model in c("sigmoid","p2","relu","binary")){

for(model in c("sigmoid","p2","relu","linear")){
# Create directories if they don't exist
base_fol <- "out/TSS/ite_abpred/BLUP120/"
dir.create(base_fol, showWarnings = FALSE, recursive = TRUE)
# Assuming folder creation is required only once
cv<-c()
cvv<-c()
# Loop over 100 iterations

cvv<-readRDS(paste0(base_fol,"/",model,"cor10"))[1:100,]
cv <-readRDS(paste0(base_fol,"/",model,"corm"))
 

# max_cv <- max(cv, na.rm = TRUE)
# min_cv <- min(cv, na.rm = TRUE)



if(model=="p2"){
 model="square"
}
max_cv <- 1
min_cv <- -1

# # Create the plot using the max and min for x and y limits
plot(cv, xlim = c(min_cv, max_cv), ylim = c(min_cv, max_cv),
     main = paste0("BLUP : ",model),ylab="Trained by A + Bpred", xlab="Trained by A + B")

# Add the 45-degree line
abline(0, 1, col = "red")

max_cvv <-  1
min_cvv <- -1

print(model)
print(table((cv[,1]-cv[,2]) < 0))
print(table((cvv[,1]-cvv[,2]) < 0))
# Create the plot using the max and min for x and y limits
plot(cvv, xlim = c(min_cvv, max_cvv), ylim = c(min_cvv, max_cvv), 
     main = paste0("BLUP : ",model),ylab="Trained by A + Bpred", xlab="Trained by A + B",
     cex=1
     #, xlab = "A", ylab = "ABpred"
     )

# Add the 45-degree line
abline(0, 1, col = "red")
# boxplot(cv,ylim=c(min_cv, max_cv), 
#      main = paste0("BLUP : ",model))
# boxplot(cvv,ylim=c(min_cvv, max_cvv), 
#      main = paste0("RF : ",model))
}


#saveRDS(cv,here)

```



# plot
```{r, fig.width=5, fig.height=5}
n <- 30
a <- 10
b <- 10
c <- 10
d <- 10
ws<- -1
w <- 1

#for(model in c("sigmoid","p2","relu","binary")){

for(model in c("sigmoid","p2","relu","linear")){
# Create directories if they don't exist
base_fol <- "out/TSS/ite_abpred/BLUP120/"
   
dir.create(base_fol, showWarnings = FALSE, recursive = TRUE)
# Assuming folder creation is required only once
cv<-c()
cvv<-c()
# Loop over 100 iterations
for (iteration in 1:10) {
 #print(iteration)
  fol <- paste0(base_fol, "TSS_",model,"_nabcd_iter", iteration, "_", n, a, b, c, d, e)
  
  # Ensure directories for each iteration
  dir.create(fol, showWarnings = FALSE, recursive = TRUE)
  dir.create(paste0(fol, "/pdf"), showWarnings = FALSE, recursive = TRUE)

  Bpred<- readRDS(paste0(fol,"/","Bpred_A"))

  res<- readRDS(paste0(fol,"/","res_abpred"))

  cor10<-t(res$resultEachModel)
  cvv<-rbind(cvv,cor10)
  corm<-rowMeans(res$resultEachModel)
  cv<-rbind(cv,corm)
}
# 
# saveRDS(cvv,paste0(base_fol,"/",model,"cor10"))
# saveRDS(cv,paste0(base_fol,"/",model,"corm"))

# cvv<-readRDS(paste0(base_fol,"/",model,"cor10"))
# cv <-readRDS(paste0(base_fol,"/",model,"corm"))
#  
# 
# max_cv <- max(cv, na.rm = TRUE)
# min_cv <- min(cv, na.rm = TRUE)



if(model=="p2"){
 model="square"
}

max_cv <-  1
min_cv <- -1

# # Create the plot using the max and min for x and y limits
plot(cv, xlim = c(min_cv, max_cv), ylim = c(min_cv, max_cv),
     main = paste0("model : ",model),ylab="Trained by A + Bpred", xlab="Trained by A")

# Add the 45-degree line
abline(0, 1, col = "red")

max_cvv <-  1
min_cvv <- -1

print(model)
print(table((cv[,1]-cv[,2]) < 0))
print(table((cvv[,1]-cvv[,2]) < 0))
# Create the plot using the max and min for x and y limits
plot(cvv, xlim = c(min_cvv, max_cvv), ylim = c(min_cvv, max_cvv), 
     main = paste0("BLUP : ",model),ylab="Trained by A + Bpred", xlab="Trained by A",
     cex=1
     #, xlab = "A", ylab = "ABpred"
     )

# Add the 45-degree line
abline(0, 1, col = "red")
boxplot(cv,ylim=c(min_cv, max_cv), 
     main = paste0("model : ",model))
boxplot(cvv,ylim=c(min_cvv, max_cvv), 
     main = paste0("model : ",model))
}


```