---
title: "83_bpred_compare"
author: "Hayato Yoshioka"
date: "2025-02-12"
output: html_document
---




```{r, fig.width=5, fig.height=5}
set.seed(123)
n <- 30
a <- 10
b <- 10
c <- 10
d <- 10
e <- 0.5
ws<- -1
w <- 1

par(pty="s")
for(model in c("sigmoid","p2","relu","linear")){
cv_r<-c()
cv_b<-c() 

for (iteration in 1:10) {

data <- simdata4(n=n, a=a, b=b, c=c, d=d, ws=ws, w=w, model=model,noise=e)
B<-data$B

base_fol <- "out/TSS/ite_abpred/rf/"
fol <- paste0(base_fol, "TSS_",model,"_nabcd_iter", iteration, "_", n, a, b, c, d, e)

Bpred<- readRDS(paste0(fol,"/","Bpred_A"))
dc<-diag(cor(B,Bpred))
cv_r<-c(cv_r,dc)

base_fol <- "out/TSS/ite_abpred/BLUP/"
fol <- paste0(base_fol, "TSS_",model,"_nabcd_iter", iteration, "_", n, a, b, c, d, e)

Bpred<- readRDS(paste0(fol,"/","Bpred_A"))
dc<-diag(cor(B,Bpred))
cv_b<-c(cv_b,dc)

}
#saveRDS(cv_r, paste0(base_fol,"/",model,"cor10_ab_r", n, a, b, c, d, e,".rds"))


cv_all<- cbind(cv_r,cv_b)
colnames(cv_all)<- paste0(c("RF","BLUP"))

base_fol <- "out/TSS/ite_abpred/rf/"
saveRDS(cv_all, paste0(base_fol,"/",model,"cor10_ab_rb", n, a, b, c, d,e,".rds"))

if(model=="p2"){
 model="square"
}

max_cvv <-  1
min_cvv <- -1

plot(cv_all[,c(2,1)], xlim = c(min_cvv, max_cvv), ylim = c(min_cvv, max_cvv), main = paste("Prediction A to B :", model))

abline(0, 1, col = "red")


}


```


```{r, fig.width=8, fig.height=8}
# 2×2のレイアウトを設定
par(mfrow = c(2, 2),pty="s")

for (model in c("linear", "relu", "p2", "sigmoid")) {

base_fol <- "out/TSS/ite_abpred/rf/"
cv_all<-readRDS(paste0(base_fol,"/",model,"cor10_ab_rb", n, a, b, c, d, e,".rds"))[1:100,]


#cv_all<- cbind(cvvr,cvvb)
colnames(cv_all)<- paste0(c("RF","BLUP"))
if(model=="p2"){
 model="square"
}

max_cvv <-  1
min_cvv <- -1

cv_all<- subset(cv_all, cv_all[,1] >= 0 | cv_all[,2] >= 0)
t_test_result <- t.test(cv_all[,1], cv_all[,2], paired = TRUE)
print(t_test_result$p.value)

plot(cv_all[,c(2,1)], xlim = c(min_cvv, max_cvv), ylim = c(min_cvv, max_cvv), main = paste("B Prediction :", model))

abline(0, 1, col = "red")
}

# レイアウトを元に戻す
par(mfrow = c(1, 1))

```



```{ fig.width=5, fig.height=5}
par(pty="s")
for(model in c("sigmoid","p2","relu","linear")){

base_fol <- "out/TSS/ite_abpred/rf/"
cvvr<-readRDS(paste0(base_fol,"/",model,"cor10_b"))[1:100,]
cvr <-readRDS(paste0(base_fol,"/",model,"corm_b"))


base_fol <- "out/TSS/ite_abpred/BLUP/"
cvvb<-readRDS(paste0(base_fol,"/",model,"cor10_b"))[1:100,]
cvb <-readRDS(paste0(base_fol,"/",model,"corm_b"))


cv_all<- cbind(cvvr,cvvb)
colnames(cv_all)<- paste0(c("RF","BLUP"))
if(model=="p2"){
 model="square"
}

max_cvv <-  1
min_cvv <- -1

plot(cv_all[,c(2,1)], xlim = c(min_cvv, max_cvv), ylim = c(min_cvv, max_cvv), main = paste("Prediction A to B :", model))

abline(0, 1, col = "red")
}
par()
```



last pred 

```{r}
library(GGally)  # for pairplot
library(ggplot2) # for additional plotting support

# Define possible folders
folders <- c("out/TSS/ite_abpred/rf/",
             "out/TSS/ite_abpred/BLUP/",
             "out/TSS/ite_abpred/b2rf/",
             "out/TSS/ite_abpred/r2b/")

# モデルごとにループ
for (model in c("sigmoid", "p2", "relu", "linear")) {
  
  cv_list <- list()  # フォルダごとのデータを格納するリスト
  
  # フォルダごとにループ
  for (i in 1:4) {
    base_fol <- folders[i]
    
    # RDSファイルの読み込み
    file_path <- paste0(base_fol, "/", model, "cor10")
    if (file.exists(file_path)) {
      cv <- readRDS(file_path)[, 1]
      
      # データフレームに変換
      if (!is.data.frame(cv)) {
        cv <- as.data.frame(cv)
      }
      
      colnames(cv) <- paste0("Folder", i)  # 列名をフォルダごとに設定
      cv_list[[i]] <- cv
    } else {
      warning(paste("File not found:", file_path))
    }
  }
  
  # すべてのフォルダのデータを結合
  if (length(cv_list) > 0) {
    cv_all <- do.call(cbind, cv_list)  # 列方向に結合
    colnames(cv_all) <- paste0("Folder", 1:length(cv_list))  # 列名を統一
    
    # Pair plot の作成
    max_cvv <-  1
    min_cvv <- -1
    
    plot(cv_all[,c(1,2)], xlim = c(min_cvv, max_cvv), ylim = c(min_cvv, max_cvv), main = paste("Prediction A to B :", model))
    
    abline(0, 1, col = "red")
  }
}

```

```{r}
library(GGally)
library(ggplot2)

# Define possible folders
folders <- c("out/TSS/ite_abpred/rf/",
             "out/TSS/ite_abpred/BLUP/",
             "out/TSS/ite_abpred/b2rf/",
             "out/TSS/ite_abpred/r2b/")

# カスタムプロット関数を定義
custom_plot <- function(data, mapping, ...) {
  ggplot(data = data, mapping = mapping) +
    geom_point(alpha = 0.6) +  # 散布図
    geom_abline(slope = 1, intercept = 0, linetype = "dashed", color = "red") +  # y=x線
    xlim(-1, 1) + ylim(-1, 1) +  # 軸範囲を固定
    theme_minimal()
}

# モデルごとにループ
for (model in c("sigmoid", "p2", "relu", "linear")) {
  
  cv_list <- list()  # フォルダごとのデータを格納するリスト
  
  # フォルダごとにループ
  for (i in 1:4) {
    base_fol <- folders[i]
    
    # RDSファイルの読み込み
    file_path <- paste0(base_fol, "/", model, "cor10")
    if (file.exists(file_path)) {
      cv <- readRDS(file_path)[, 1]
      
      # データフレームに変換
      if (!is.data.frame(cv)) {
        cv <- as.data.frame(cv)
      }
      
      colnames(cv) <- paste0("Folder", i)  # 列名をフォルダごとに設定
      cv_list[[i]] <- cv
    } else {
      warning(paste("File not found:", file_path))
    }
  }
  
  # すべてのフォルダのデータを結合
  if (length(cv_list) > 0) {
    cv_all <- do.call(cbind, cv_list)  # 列方向に結合
    colnames(cv_all) <- paste0("Folder", 1:length(cv_list))  # 列名を統一
    
    # Pair plot の作成
    print(
      ggpairs(cv_all,
              lower = list(continuous = custom_plot),  # 下三角プロット
              upper = list(continuous = custom_plot),  # 上三角プロット
              title = paste("Pairplot for Model:", model))
    )
  }
}

```



```{r, fig.width=5, fig.height=5}

for(model in c("sigmoid","p2","relu","linear")){

base_fol <- "out/TSS/ite_abpred/rf/"
cvvr<-readRDS(paste0(base_fol,"/",model,"cor10_b"))[1:100,]
cvr <-readRDS(paste0(base_fol,"/",model,"corm_b"))


base_fol <- "out/TSS/ite_abpred/BLUP/"
cvvb<-readRDS(paste0(base_fol,"/",model,"cor10_b"))[1:100,]
cvb <-readRDS(paste0(base_fol,"/",model,"corm_b"))


cv_all<- cbind(cvvr,cvvb)
colnames(cv_all)<- paste0(c("RF","BLUP"))
if(model=="p2"){
 model="square"
}

max_cvv <-  1
min_cvv <- -1

plot(cv_all[,c(2,1)], xlim = c(min_cvv, max_cvv), ylim = c(min_cvv, max_cvv), main = paste("Prediction A to B :", model))

abline(0, 1, col = "red")
}
```


```{r}

```

