
BLUP

```{r,message=F,include=FALSE,echo=FALSE}
library(purrr)
library(stringr)
library(dplyr)
library(corrplot)
source("Script/MyFunctions.R")
library(RAINBOWR)
library(DiagrammeR)
library(tictoc)
library(doSNOW)
library(ranger)
library(here)
library(psych)
library(doFuture)
library(MASS)
library(rrBLUP)
require(ranger)
library(doSNOW)
#library(sigmoid)

```



#A to B

run
```{r}
# Setup before loop
set.seed(123)
n <- 30
a <- 10
b <- 10
c <- 10
d <- 10
ws<- -1
w <- 1

#for(model in c("sigmoid","linear")){
#for(model in c("tanh")){
for(model in c("sigmoid","p2","relu","linear")){
#for(model in c("p2","relu","linear")){
print(model)
# Create directories if they don't exist
base_fol <- "out/TSS/ite_abpred/BLUP/"
dir.create(base_fol, showWarnings = FALSE, recursive = TRUE)
# Assuming folder creation is required only once
cv<-c()
cvv<-c()
# Loop over 100 iterations
for (iteration in 1:10) {
 print(iteration)
  fol <- paste0(base_fol, "TSS_",model,"_nabcd_iter", iteration, "_", n, a, b, c, d)
  
  # Ensure directories for each iteration
  dir.create(fol, showWarnings = FALSE, recursive = TRUE)
  dir.create(paste0(fol, "/pdf"), showWarnings = FALSE, recursive = TRUE)

  data <- simdata4(n=n, a=a, b=b, c=c, d=d, ws=ws, w=w, model=model,noise=0.1)
  
  A <- data$A
  B <- data$B
  C <- data$C
  D <- data$D
  
  
  Z<-diag(n)
  
  KZA<- list(A= list(K = bt(A), Z = Z))
  #KZB<- list(A= list(K = bt(B), Z = Z))
  #KZC<- list(A= list(K = bt(C), Z = Z))
  #KZD<- list(A= list(K = bt(D), Z = Z))
  
  # Prediction and saving results
  ZETAlist <- list(A=KZA)
  names(ZETAlist)<-c("KZA")
  
  Y <- B
  
  res<- getBLUP_simulation(ZETAlist,Y)
  #res <- getRF(RFlist, Y)
  
  saveRDS(res, paste0(fol, "/resb_a"))
  res<- readRDS(paste0(fol, "/resb_a"))
  
  Bpred <- res$predictDataList[[1]]
  
  saveRDS(Bpred, paste0(fol, "/Bpred_A"))
  
  Bpred<- readRDS(paste0(fol,"/","Bpred_A"))
  
  

  cor10<-t(res$resultEachModel)
  cvv<-rbind(cvv,cor10)
  corm<-rowMeans(res$resultEachModel)
  cv<-rbind(cv,corm)

}

saveRDS(cvv,paste0(base_fol,"/",model,"cor10_b"))
saveRDS(cv,paste0(base_fol,"/",model,"corm_b"))


}


```

plot
```{r}
# Setup before loop
set.seed(123)
n <- 30
a <- 10
b <- 10
c <- 10
d <- 10
ws<- -1
w <- 1

#for(model in c("sigmoid","linear")){
#for(model in c("tanh")){
for(model in c("sigmoid","p2","relu","linear")){
#for(model in c("p2","relu","linear")){
print(model)
# Create directories if they don't exist
base_fol <- "out/TSS/ite_abpred/BLUP/"
dir.create(base_fol, showWarnings = FALSE, recursive = TRUE)
# Assuming folder creation is required only once
cv<-c()
cvv<-c()
# Loop over 100 iterations
for (iteration in 1:10) {
 print(iteration)
  fol <- paste0(base_fol, "TSS_",model,"_nabcd_iter", iteration, "_", n, a, b, c, d)
  
  # Ensure directories for each iteration
  dir.create(fol, showWarnings = FALSE, recursive = TRUE)
  dir.create(paste0(fol, "/pdf"), showWarnings = FALSE, recursive = TRUE)

  data <- simdata5(n=n, a=a, b=b, c=c, d=d, ws=ws, w=w, model=model,noise=0.1)
  
  A <- data$A
  B <- data$B
  C <- data$C
  D <- data$D
  
  Z<-diag(n)
  
  KZA<- list(A= list(K = bt(A), Z = Z))
  #KZB<- list(A= list(K = bt(B), Z = Z))
  #KZC<- list(A= list(K = bt(C), Z = Z))
  #KZD<- list(A= list(K = bt(D), Z = Z))
  
  # Prediction and saving results
  ZETAlist <- list(A=KZA)
  names(ZETAlist)<-c("KZA")
  
  Y <- B
  
  #res<- getBLUP_simulation(ZETAlist,Y)
  #res <- getRF(RFlist, Y)
  
  #saveRDS(res, paste0(fol, "/resb_a"))
  res<- readRDS(paste0(fol, "/resb_a"))
  
  Bpred <- res$predictDataList[[1]]
  
  saveRDS(Bpred, paste0(fol, "/Bpred_A"))
  
  Bpred<- readRDS(paste0(fol,"/","Bpred_A"))
  
  

  cor10<-t(res$resultEachModel)
  cvv<-rbind(cvv,cor10)
  corm<-rowMeans(res$resultEachModel)
  cv<-rbind(cv,corm)

}

saveRDS(cvv,paste0(base_fol,"/",model,"cor10_b"))
saveRDS(cv,paste0(base_fol,"/",model,"corm_b"))

}

```


